import os

API_KEY = os.environ.get('ALIEXPRESS_DROPSHIP_API_KEY')
API_SECRET = os.environ.get('ALIEXPRESS_DROPSHIP_API_SECRET')
API_TOKEN = os.environ.get('ALIEXPRESS_DROPSHIP_API_TOKEN')

AFFILIATE_API_KEY = os.environ.get('ALIEXPRESS_AFFILIATE_API_KEY')
AFFILIATE_API_SECRET = os.environ.get('ALIEXPRESS_AFFILIATE_API_SECRET')
