import os

API_KEY = os.environ.get('ALIEXPRESS_DROPSHIP_API_KEY')
API_SECRET = os.environ.get('ALIEXPRESS_DROPSHIP_API_SECRET')

API_KEY_ADMITAD = os.environ.get('ALIEXPRESS_DROPSHIP_API_KEY_ADMITAD')
API_SECRET_ADMITAD = os.environ.get('ALIEXPRESS_DROPSHIP_API_SECRET_ADMITAD')

DEFAULT_USER = os.environ.get('ALIEXPRESS_DEFAULT_USER')

AFFILIATE_API_KEY = os.environ.get('ALIEXPRESS_AFFILIATE_API_KEY')
AFFILIATE_API_SECRET = os.environ.get('ALIEXPRESS_AFFILIATE_API_SECRET')
