# Generated by Django 3.2.14 on 2022-11-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0262_auto_20221111_1742'),
        ('shopify_orders', '0039_shopifyfulfillementrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopifyfulfillementrequest',
            unique_together={('store', 'fulfillment_order_id')},
        ),
    ]
