# Generated by Django 3.2.14 on 2022-11-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_orders', '0040_alter_shopifyfulfillementrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyfulfillementrequest',
            name='request_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
