# Generated by Django 2.2.27 on 2022-04-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fields', models.TextField(default='[]', help_text='''Credentials fields in format <pre>
                    [{
                        "name": "api_key",
                        "label": "Api Key",
                        "type": "password/text"
                    }]</pre>''')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='test_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='carrier_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.CarrierType'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
