# Generated by Django 2.2.27 on 2022-04-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20220411_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriertype',
            name='fields',
            field=models.TextField(default='[]', help_text='Credentials fields in format <pre>\n    [{\n        "name": "api_key",\n        "label": "Api Key",\n        "type": "password/text"\n    }]</pre>'),
        ),
        migrations.AlterUniqueTogether(
            name='carrier',
            unique_together={('account', 'reference')},
        ),
    ]
