# Generated by Django 2.2.27 on 2022-04-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20220412_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
