# Generated by Django 2.2.27 on 2022-04-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_auto_20220413_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='label_url',
            new_name='source_label_url',
        ),
    ]
