# Generated by Django 2.2.27 on 2022-04-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_auto_20220419_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='store_order_id',
            new_name='store_order_number',
        ),
    ]
