# Generated by Django 2.2.27 on 2022-05-15 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_auto_20220425_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='hs_tariff',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Weight (oz)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='purchases', to='logistics.Listing'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_data_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
