# Generated by Django 2.2.27 on 2022-05-30 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0010_auto_20220515_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='logistics_balance',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='title',
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_inventory_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_tariff',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=0,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='logistics_products',
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name="Resident's Full Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='logistics.Variant'),
        ),
        migrations.CreateModel(
            name='AccountCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_charge_id', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Stripe Charge ID')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='logistics.AccountBalance')),
            ],
        ),
    ]
