# Generated by Django 2.2.27 on 2022-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_auto_20220530_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants_map',
            field=models.TextField(default='[]'),
        ),
    ]
