# Generated by Django 2.2.27 on 2022-06-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_product_variants_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dropified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
