# Generated by Django 3.2.13 on 2022-07-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carriertype',
            name='logo_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
