# Generated by Django 3.2.13 on 2022-08-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_order_label_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='label_at',
            new_name='paid_at',
        ),
    ]
