# Generated by Django 3.2.13 on 2022-08-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_rename_label_at_order_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcredit',
            name='order',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='refunds',
                to='logistics.order'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Asked for refund at'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('submitted', 'Submitted'),
                    ('not_applicable', 'Not Applicable'),
                    ('refunded', 'Refunded'),
                    ('rejected', 'Rejected')
                ],
                max_length=255,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Refund processed at'),
        ),
        migrations.AlterField(
            model_name='accountcredit',
            name='stripe_charge_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Stripe Charge ID'),
        ),
    ]
