# Generated by Django 3.2.13 on 2022-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_auto_20220823_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Weight (oz)'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='height',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Height (inches)'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='length',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Length (inches)'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='weight',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Weight (oz)'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='width',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Width (inches)'),
        ),
    ]
