# Generated by Django 3.2.14 on 2022-10-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_auto_20220907_1419'),
        ('logistics', '0020_auto_20220908_2359'),
    ]

    operations = [
    ]
