# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-29 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_core', '0012_wooordertrack_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='woostore',
            name='auto_fulfill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='woostore',
            name='list_index',
            field=models.IntegerField(default=0),
        ),
    ]
