# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_core', '0015_auto_20190725_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='wooproduct',
            name='bundle_map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wooproduct',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
