# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_core', '0015_auto_20190725_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='wooproduct',
            name='monitor_id',
            field=models.IntegerField(null=True),
        ),
    ]
