# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_core', '0016_wooproduct_monitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wooproduct',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
