# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_core', '0019_auto_20191106_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wooboard',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
