# Generated by Django 2.2.16 on 2021-09-30 20:14

from django.db import migrations, models
import django.db.models.deletion
import woocommerce_core.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_core', '0025_wooproduct_boards_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('order_id', models.IntegerField(db_index=True)),
                ('date_created', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woocommerce_core.WooStore')),
            ],
            options={
                'verbose_name': 'Woo Order',
                'verbose_name_plural': 'Woo Orders',
            },
            bases=(woocommerce_core.mixins.WooAPIDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WooSyncStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=32)),
                ('sync_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Completed'), (3, 'Unauthorized'), (4, 'Error'), (5, 'Disabled'), (6, 'Reset')], default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('pending_orders', models.TextField(blank=True, null=True)),
                ('revision', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elastic', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_statuses', to='woocommerce_core.WooStore')),
            ],
            options={
                'verbose_name': 'Woo Sync Status',
                'verbose_name_plural': 'Woo Sync Statuses',
            },
        ),
        migrations.CreateModel(
            name='WooOrderShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=3)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='woocommerce_core.WooOrder')),
            ],
            options={
                'verbose_name': 'Woo Order Shipping Address',
                'verbose_name_plural': 'Woo Order Shipping Addresses',
            },
            bases=(woocommerce_core.mixins.WooAPIDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WooOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('line_id', models.IntegerField(db_index=True)),
                ('product_id', models.IntegerField(db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woocommerce_core.WooOrder')),
            ],
            options={
                'verbose_name': 'Woo Order Line',
                'verbose_name_plural': 'Woo Order lines',
            },
            bases=(woocommerce_core.mixins.WooAPIDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WooOrderBillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='woocommerce_core.WooOrder')),
            ],
            options={
                'verbose_name': 'Woo Order Billing Address',
                'verbose_name_plural': 'Woo Order Billing Addresses',
            },
            bases=(woocommerce_core.mixins.WooAPIDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WooWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=60)),
                ('webhook_id', models.BigIntegerField(default=0, verbose_name='Webhook ID')),
                ('call_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woocommerce_core.WooStore')),
            ],
            options={
                'verbose_name': 'WooCommerce Order Webhooks',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'topic')},
            },
        ),
    ]
