# Generated by Django 3.2.13 on 2022-06-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichannel_products_core', '0001_initial'),
        ('woocommerce_core', '0026_wooorder_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wooproduct',
            name='master_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='multichannel_products_core.masterproduct'),
        ),
    ]
