# Generated by Django 2.2.13 on 2020-07-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0002_addonusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonusage',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Added to invoice or not'),
        ),
    ]
