# Generated by Django 2.2.13 on 2020-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0004_auto_20200716_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonusage',
            name='processed',
        ),
        migrations.AddField(
            model_name='addonusage',
            name='billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
