# Generated by Django 2.2.13 on 2020-07-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0004_addon_key_benfits'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
