# Generated by Django 2.2.13 on 2020-07-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0005_addon_youtube_url'),
        ('addons_core', '0006_addon_trial_period_days'),
    ]

    operations = [
    ]
