# Generated by Django 2.2.12 on 2020-08-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0007_merge_20200723_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('short_description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort Order')),
                ('category_tag', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='addon',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='addons', to='addons_core.Category'),
        ),
    ]
