# Generated by Django 2.2.15 on 2020-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0008_auto_20200805_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='faq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
