# Generated by Django 2.2.15 on 2020-08-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0009_addon_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='vimeo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
