# Generated by Django 2.2.15 on 2020-08-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0011_auto_20200818_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
