# Generated by Django 2.2.16 on 2020-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0012_auto_20200826_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addonusage',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='addonusage',
            name='billed_at',
        ),
        migrations.AddField(
            model_name='addonusage',
            name='billed_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addonusage',
            name='billing_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addonusage',
            name='interval_day',
            field=models.IntegerField(default=0),
        ),
    ]
