# Generated by Django 2.2.16 on 2020-10-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0014_auto_20200923_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.CharField(blank=True, default='', editable=False, max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('trial_period_days', models.IntegerField(default=0)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('interval', models.IntegerField(choices=[(None, ''), (0, 'Day'), (1, 'Week'), (2, 'Month'), (3, 'Year')], null=True, default=None)),
                ('interval_count', models.IntegerField(default=1, verbose_name='frequency')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.RemoveField(
            model_name='addonusage',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='addonusage',
            name='billed_to',
        ),
        migrations.RemoveField(
            model_name='addonusage',
            name='billing_day',
        ),
        migrations.RemoveField(
            model_name='addonusage',
            name='interval_day',
        ),
        migrations.AddField(
            model_name='addon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addon',
            name='variant_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='addons_core.Addon'),
        ),
        migrations.AddField(
            model_name='addonusage',
            name='next_billing',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='addonusage',
            name='start_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='addonusage',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addonusage',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AddonPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price_descriptor', models.CharField(blank=True, default='', max_length=255)),
                ('iterations', models.IntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='addons_core.AddonBilling')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='addonbilling',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='addons_core.Addon'),
        ),
        migrations.AddField(
            model_name='addonusage',
            name='billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='addons_core.AddonBilling'),
        ),
        migrations.AddField(
            model_name='addonusage',
            name='price_after_cancel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addons_core.AddonPrice'),
        ),
    ]
