# Generated by Django 2.2.16 on 2020-11-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0015_auto_20201020_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonusage',
            name='cancel_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
