# Generated by Django 2.2.16 on 2020-12-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0016_addonusage_cancel_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='churnzero_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
