# Generated by Django 2.2.16 on 2020-12-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0018_auto_20201218_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='store_types',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
