# Generated by Django 2.2.16 on 2021-01-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0019_addon_store_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='stores',
            field=models.PositiveIntegerField(default=0, verbose_name='Add store limit'),
        ),
    ]
