# Generated by Django 2.2.16 on 2021-02-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0020_addon_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='trial_period_days',
        ),
    ]
