# Generated by Django 2.2.16 on 2022-01-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0021_auto_20210204_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='limit_addon',
            field=models.BooleanField(default=False, verbose_name="This addon enhances limit & doesn't require permission"),
        ),
    ]
