# Generated by Django 2.2.24 on 2022-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0022_addon_limit_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='sales_fees_adjust_free_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Increase Fulfilment Fees free Limit (amount in USD)'),
        ),
        migrations.AddField(
            model_name='addon',
            name='sales_fees_adjust_free_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Increase Fulfilment Fees free Limit (count of orders)'),
        ),
    ]
