# Generated by Django 2.2.24 on 2022-02-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0023_auto_20220117_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='auto_fulfill_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Add Auto Fulfill Limit'),
        ),
    ]
