# Generated by Django 3.2.13 on 2022-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0024_addon_auto_fulfill_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='suredone_orders_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Add SureDone Orders Limit'),
        ),
    ]
