# Generated by Django 3.2.14 on 2022-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_core', '0025_addon_suredone_orders_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='suredone_stores',
            field=models.PositiveIntegerField(default=0, verbose_name='Add SureDone Channels Limit'),
        ),
    ]
