# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-20 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supplements.mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PLSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('tags', models.TextField()),
                ('shipstation_sku', models.CharField(blank=True, max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label_template_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, supplements.mixin.PLSupplementMixin),
        ),
        migrations.CreateModel(
            name='PLSupplementImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('image_url', models.URLField()),
                ('pl_supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supplements.PLSupplement')),
            ],
        ),
        migrations.CreateModel(
            name='UserSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('tags', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pl_supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pl_supplements', to='supplements.PLSupplement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_supplements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
