# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSupplementLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('awaiting', 'Awaiting Review'), ('rejected', 'Rejected')], default='awaiting', max_length=8)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='supplements.UserSupplement')),
            ],
        ),
        migrations.AddField(
            model_name='usersupplement',
            name='current_label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplements.UserSupplementLabel'),
        ),
    ]
