# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0002_add_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSupplementImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('image_url', models.URLField()),
                ('user_supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supplements.UserSupplement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
