# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-17 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplements', '0003_add_user_supplement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('new_status', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='supplements.UserSupplementLabel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usersupplement',
            name='current_label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_label_of', to='supplements.UserSupplementLabel'),
        ),
    ]
