# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0004_add_label_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupplement',
            name='shipstation_sku',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
