# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supplements.mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplements', '0005_add_sku_in_user_supplement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLSOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_transaction_id', models.CharField(max_length=50)),
                ('shipstation_id', models.CharField(blank=True, default='', max_length=50)),
                ('order_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('processing', 'Processing')], default='processing', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pls_payments', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, supplements.mixin.PLSOrderMixin),
        ),
        migrations.CreateModel(
            name='PLSOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('line_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pls_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='supplements.PLSOrder')),
            ],
            bases=(models.Model, supplements.mixin.PLSOrderLineMixin),
        ),
        migrations.AlterUniqueTogether(
            name='plsorderline',
            unique_together=set([('order_id', 'line_id')]),
        ),
    ]
