# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0006_add_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plsorder',
            name='shipstation_id',
        ),
        migrations.AddField(
            model_name='plsorder',
            name='shipstation_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='plsorder',
            name='store_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plsorder',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble')], default='shopify', max_length=7),
        ),
        migrations.AddField(
            model_name='plsorderline',
            name='shipstation_key',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plsorderline',
            name='sku',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plsorderline',
            name='store_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plsorderline',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble')], default='shopify', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='plsorderline',
            unique_together=set([('store_type', 'store_id', 'order_id', 'line_id')]),
        ),
    ]
