# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0001_initial'),
        ('supplements', '0008_add_payout_and_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plsupplementimage',
            name='pl_supplement',
        ),
        migrations.RemoveField(
            model_name='plsupplement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='plsupplement',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='plsupplement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plsupplement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='plsupplement',
            name='shipstation_sku',
        ),
        migrations.RemoveField(
            model_name='plsupplement',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='plsupplement',
            name='title',
        ),
        migrations.AddField(
            model_name='plsupplement',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_common.Product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PLSupplementImage',
        ),
    ]
