# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0011_add_status_and_amount_to_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupplementlabel',
            name='pdf_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
