# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-12 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0012_add_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plsorderline',
            name='sku',
        ),
    ]
