# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0013_remove_sku_from_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersupplement',
            name='shipstation_sku',
        ),
        migrations.AddField(
            model_name='usersupplementlabel',
            name='sku',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
