# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0014_fix_sku_logic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersupplementlabel',
            name='pdf_url',
        ),
    ]
