# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0015_remove_pdf_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsorderline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
