# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0016_add_quantity_to_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsorder',
            name='sale_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plsorderline',
            name='sale_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
