# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supplements.mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplements', '0018_add_shipping_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizeNetCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255, null=True, verbose_name='Authorize.net Customer ID')),
                ('payment_id', models.CharField(max_length=255, null=True, verbose_name='Authorize.net Customer Payment ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorize_net_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorize.net Customer',
                'verbose_name_plural': 'Authorize.net Customers',
            },
            bases=(models.Model, supplements.mixin.AuthorizeNetCustomerMixin),
        ),
    ]
