# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0019_authorizenetcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plsorder',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart')], default='shopify', max_length=7),
        ),
        migrations.AlterField(
            model_name='plsorderline',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart')], default='shopify', max_length=7),
        ),
    ]
