# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0021_use_order_info_from_product_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsorderline',
            name='sku',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plsorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plsorder_product_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
