# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-14 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0022_order_dry'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsorder',
            name='wholesale_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plsorderline',
            name='wholesale_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plsupplement',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
