# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-15 07:49
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify

from shopified_core.shipping_helper import get_counrties_list as get_countries_list


def add_shipping_groups(apps, schema_editor):
    ShippingGroup = apps.get_model('supplements', 'ShippingGroup')
    countries = get_countries_list()
    states = """
        Alabama
        Alaska
        Arizona
        Arkansas
        California
        Colorado
        Connecticut
        Delaware
        Florida
        Georgia
        Hawaii
        Idaho
        Illinois
        Indiana
        Iowa
        Kansas
        Kentucky
        Louisiana
        Maine
        Maryland
        Massachusetts
        Michigan
        Minnesota
        Mississippi
        Missouri
        Montana
        Nebraska
        Nevada
        New Hampshire
        New Jersey
        New Mexico
        New York
        North Carolina
        North Dakota
        Ohio
        Oklahoma
        Oregon
        Pennsylvania
        Rhode Island
        South Carolina
        South Dakota
        Tennessee
        Texas
        Utah
        Vermont
        Virginia
        Washington
        West Virginia
        Wisconsin
        Wyoming
    """

    ShippingGroup.objects.all().delete()
    groups = [dict(slug=s, name=c, locations=c) for s, c in countries]

    states = [s.strip() for s in states.split('\n') if s.strip()]
    for state in states:
        slug = f"us-{slugify(state)}"
        name = f"{state}, USA"
        groups.append(dict(slug=slug, name=name, locations=state))

    for group in groups:
        ShippingGroup.objects.create(
            immutable=True,
            **group,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0024_shippinggroup'),
    ]

    operations = [
        migrations.RunPython(add_shipping_groups),
    ]
