# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0025_add_shipping_group_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plsupplement',
            name='shipping_countries',
        ),
        migrations.AddField(
            model_name='plsupplement',
            name='shipping_countries',
            field=models.ManyToManyField(to='supplements.ShippingGroup'),
        ),
    ]
