# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0027_plsorder_is_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='authenticity_certificate_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plsupplement',
            name='product_information',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
