# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-07 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0029_labelsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='label_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_size', to='supplements.LabelSize'),
        ),
    ]
