# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-12 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0030_plsupplement_label_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsorder',
            name='batch_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
