# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0031_plsorder_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupplementlabel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('awaiting', 'In Review'), ('rejected', 'Rejected')], default='draft', max_length=8),
        ),
    ]
