# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0032_auto_20200224_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
