# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 07:27
from __future__ import unicode_literals

from django.db import migrations
from supplements.models import MockupType


def add_mockup_types(apps, schema_editor):
    MockupType.objects.create(
        slug='bottle',
        name='2.5 x 7.0 Bottle',
    )
    MockupType.objects.create(
        slug='container',
        name='2.5 x 7.0 Container',
    )
    MockupType.objects.create(
        slug='tincture',
        name='30ml Tincture',
    )

def reverse_func(apps, schema_editor):
    MockupType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0033_mockuptype'),
    ]

    operations = [
        migrations.RunPython(add_mockup_types, reverse_func)
    ]
