# Generated by Django 1.11.28 on 2020-03-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0036_add_supplement_mockup_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsize',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='labelsize',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
