# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0037_shippinggroup_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
