# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-02 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0039_auto_20200401_1140'),
        ('supplements', '0037_auto_20200326_1144'),
    ]

    operations = [
    ]
