# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-10 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0042_auto_20200408_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plsupplement',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
