# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0038_auto_20200408_2127'),
        ('supplements', '0043_auto_20200410_0845'),
    ]

    operations = [
    ]
