# Generated by Django 2.2.12 on 2020-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0045_fill_shipping_group_data_20200413_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
