# Generated by Django 2.2.12 on 2020-04-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0046_plsupplement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plsorder',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce')], default='shopify', max_length=15),
        ),
        migrations.AlterField(
            model_name='plsorderline',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce')], default='shopify', max_length=15),
        ),
    ]
