# Generated by Django 2.2.12 on 2020-05-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0049_auto_20200430_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='inventory',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
