# Generated by Django 2.2.12 on 2020-05-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0050_plsupplement_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='msrp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MSRP'),
        ),
    ]
