# Generated by Django 2.2.12 on 2020-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0051_plsupplement_msrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupplement',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
