# Generated by Django 2.2.12 on 2020-05-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0052_auto_20200509_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupplement',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
