# Generated by Django 2.2.12 on 2020-05-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0053_usersupplement_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelcomment',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
