# Generated by Django 2.2.12 on 2020-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0055_usersupplement_label_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='shipping_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
