# Generated by Django 2.2.12 on 2020-06-11 02:13

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).create(
        slug='2500cc-powder-container',
        name='2500cc Powder Container',
    )

    MockupType.objects.using(db_alias).create(
        slug='sour-gummies-bottle',
        name='Sour Gummies Bottle',
    )


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).filter(slug__in=[
        '2500cc-powder-container',
        'sour-gummies-bottle',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0057_payout_shipping_cost'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
