# Generated by Django 2.2.12 on 2020-06-25 21:32

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).create(
        slug='cdb-gummies',
        name='CDB Gummies',
    )

    MockupType.objects.using(db_alias).create(
        slug='1oz-pump-bottle',
        name='1oz Pump Bottle',
    )

    MockupType.objects.using(db_alias).create(
        slug='2oz-pump-bottle',
        name='2oz Pump Bottle',
    )

    MockupType.objects.using(db_alias).create(
        slug='exfoliating-cleanser',
        name='Exfoliating Cleanser',
    )

    MockupType.objects.using(db_alias).create(
        slug='4oz-cosmetic-jar',
        name='4oz Cosmetic Jar',
    )


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).filter(slug__in=[
        'cdb-gummies',
        '1oz-pump-bottle',
        '2oz-pump-bottle',
        'exfoliating-cleanser',
        '4oz-cosmetic-jar',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0058_new_mockup_types'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
