# Generated by Django 2.2.13 on 2020-07-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0059_special_mockup_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsorder',
            name='shipping_address_hash',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
