# Generated by Django 2.2.13 on 2020-07-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0061_auto_20200708_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupplement',
            name='seen_users',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
