# Generated by Django 2.2.13 on 2020-07-09 06:57

import json

from django.db import migrations
from django.db.models import Q


def forwards_func(apps, schema_editor):
    UserSupplement = apps.get_model('supplements', 'UserSupplement')

    supplement_ids = UserSupplement.objects.exclude(Q(current_label__isnull=True)
                                                    | Q(current_label__status='draft')) \
                                           .values_list('id', flat=True)[20:]

    UserSupplement.objects.filter(id__in=list(supplement_ids)) \
                          .update(seen_users=json.dumps(['All']))


def reverse_func(apps, schema_editor):
    UserSupplement = apps.get_model('supplements', 'UserSupplement')

    UserSupplement.objects.update(seen_users='')


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0062_usersupplement_seen_users'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
