# Generated by Django 2.2.12 on 2020-07-24 13:53

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).bulk_create([
        MockupType(slug='4oz-pump-bottle', name='4oz Pump Bottle'),
        MockupType(slug='44oz-jar-black-lid', name='44oz Jar Black Lid'),
        MockupType(slug='colored-container-dogtreats', name='Dog Treats'),
        MockupType(slug='32oz-jar-black-lid', name='32oz Jar Black Lid'),
        MockupType(slug='16oz-jar-black-lid', name='16oz Jar Black Lid'),
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).filter(slug__in=[
        '4oz-pump-bottle',
        '44oz-jar-black-lid',
        'colored-container-dogtreats',
        '32oz-jar-black-lid',
        '16oz-jar-black-lid',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0063_auto_20200709_0657'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
