# Generated by Django 2.2.13 on 2020-08-20 19:43

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).bulk_create([
        MockupType(slug='4oz-jar', name='4oz Jar (Plain Lid)'),
        MockupType(slug='20oz-black-jar', name='20oz Black Jar'),
        MockupType(slug='8oz-bottle', name='8oz Clear Jar'),
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).filter(slug__in=[
        '4oz-jar', '20oz-black-jar', '8oz-bottle'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0066_auto_20200730_0745'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
