# Generated by Django 2.2.15 on 2020-09-28 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('supplements', '0068_plsorderline_shipping_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUnpaidOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
    ]
