# Generated by Django 2.2.16 on 2020-11-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0070_basketitem_basketorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plsorder',
            name='stripe_transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
