# Generated by Django 2.2.16 on 2020-11-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0071_auto_20201125_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsorder',
            name='duties',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plsorder',
            name='taxes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plsupplement',
            name='hs_code',
            field=models.CharField(default='6116.10.00', max_length=255, null=True, verbose_name='HS (Harmonized System) code'),
        ),
    ]
