# Generated by Django 2.2.16 on 2020-12-09 14:34

from django.db import migrations


def forwards_func(apps, schema_editor):
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).create(
        slug='coffee-bag',
        name='Coffee Bag',
    )


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    MockupType = apps.get_model('supplements', 'MockupType')
    db_alias = schema_editor.connection.alias

    MockupType.objects.using(db_alias).filter(slug__in=[
        'coffee-bag',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0071_auto_20201125_1807'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
