# Generated by Django 2.2.16 on 2020-12-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0072_new_coffee_mockup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizenetcustomer',
            name='customer_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Profile ID'),
        ),
        migrations.AlterField(
            model_name='authorizenetcustomer',
            name='payment_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Payment Profile ID'),
        ),
    ]
