# Generated by Django 2.2.16 on 2020-12-09 13:49

from django.db import migrations


def forwards_func(apps, schema_editor):
    PLSOrder = apps.get_model('supplements', 'PLSOrder')

    for order in PLSOrder.objects.filter(is_fulfilled=True,
                                         payout__isnull=False):
        order.order_items.update(line_payout=order.payout)


def reverse_func(apps, schema_editor):
    PLSOrderLine = apps.get_model('supplements', 'PLSOrderLine')

    PLSOrderLine.objects.update(line_payout=None)


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0072_auto_20201209_1344'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
