# Generated by Django 2.2.16 on 2020-12-09 13:50

from django.db import migrations


def forwards_func(apps, schema_editor):
    ProductSupplier = apps.get_model('product_common', 'ProductSupplier')
    db_alias = schema_editor.connection.alias

    ProductSupplier.objects.using(db_alias).bulk_create([
        ProductSupplier(slug='dropified', title='Dropified', profit_percentage=25),
        ProductSupplier(slug='tlg', title='TLG', profit_percentage=25),
        ProductSupplier(slug='pls', title='PLS', profit_percentage=50),
        ProductSupplier(slug='hurryhub', title='HurryHub', profit_percentage=50, is_shipping_supplier=True),
    ])


def reverse_func(apps, schema_editor):
    ProductSupplier = apps.get_model('product_common', 'ProductSupplier')
    db_alias = schema_editor.connection.alias

    ProductSupplier.objects.using(db_alias).filter(slug__in=[
        'dropified', 'tlg', 'pls', 'hurryhub'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0075_auto_20201209_1349'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
