# Generated by Django 2.2.16 on 2020-12-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0072_new_coffee_mockup'),
        ('supplements', '0075_remove_plsorder_payout'),
    ]

    operations = [
    ]
