# Generated by Django 2.2.16 on 2020-12-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0076_auto_20201209_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plsorder',
            name='payout',
        ),
    ]
