# Generated by Django 2.2.16 on 2021-01-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0077_remove_plsorder_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsorder',
            name='duties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plsorder',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plsupplement',
            name='hs_code',
            field=models.CharField(default='2936.29.50.50', max_length=255, null=True, verbose_name='HS (Harmonized System) code'),
        ),
        migrations.AlterField(
            model_name='plsorder',
            name='amount',
            field=models.IntegerField(verbose_name='Total amount'),
        ),
    ]
