# Generated by Django 2.2.16 on 2021-01-13 00:39

from django.db import migrations, models
from django.utils.text import slugify


def forward_func(apps, schema_editor):
    LabelSize = apps.get_model('supplements', 'LabelSize')
    for label_size in LabelSize.objects.all():
        if label_size.width < label_size.height:
            label_size.size = f"{label_size.width}x{label_size.height}"
        else:
            label_size.size = f"{label_size.height}x{label_size.width}"
        label_size.save()


def reverse_func(apps, schema_editor):
    LabelSize = apps.get_model('supplements', 'LabelSize')
    for label_size in LabelSize.objects.all():
        label_size.width, label_size.height = label_size.size.split('x')
        label_size.slug = slugify(label_size.size)
        label_size.save()


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0078_auto_20210114_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsize',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(forward_func, reverse_func),
        migrations.AlterField(
            model_name='labelsize',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='labelsize',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labelsize',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='labelsize',
            name='height',
        ),
        migrations.RemoveField(
            model_name='labelsize',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='labelsize',
            name='width',
        ),
    ]
