# Generated by Django 2.2.18 on 2021-03-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0080_auto_20210119_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mockuptype',
            options={'ordering': ('name',)},
        ),
    ]
