# Generated by Django 2.2.18 on 2021-04-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0082_refundpayments_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersupplementlabel',
            options={'ordering': ('-created_at',)},
        ),
    ]
