# Generated by Django 2.2.18 on 2021-05-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0085_auto_20210518_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
