# Generated by Django 2.2.24 on 2021-09-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0087_auto_20210802_1543'),
        ('supplements', '0087_auto_20210921_1535'),
    ]

    operations = [
    ]
