# Generated by Django 2.2.24 on 2021-10-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0088_merge_20210921_2233'),
        ('supplements', '0088_auto_20210914_1346'),
    ]

    operations = [
    ]
