# Generated by Django 3.2.13 on 2022-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0090_auto_20220218_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='is_discontinued',
            field=models.BooleanField(default=False),
        ),
    ]
