# Generated by Django 3.2.13 on 2022-06-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0091_plsupplement_is_discontinued'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plsupplement',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
