# Generated by Django 3.2.13 on 2022-06-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0092_auto_20220613_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipStationAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('api_key', models.CharField(max_length=500)),
                ('api_secret', models.CharField(max_length=500)),
                ('api_url', models.URLField(default='https://ssapi.shipstation.com')),
                ('max_retries', models.IntegerField(default=5)),
                ('send_timeout', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='plsupplement',
            name='shipstation_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplements.shipstationaccount'),
        ),
    ]
