# Generated by Django 2.2.27 on 2022-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0093_auto_20220621_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plsorder',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('ebay', 'eBay'), ('fb', 'Facebook'), ('google', 'Google'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce'), ('mybasket', 'MyBasket')], default='shopify', max_length=15),
        ),
        migrations.AlterField(
            model_name='plsorderline',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('ebay', 'eBay'), ('fb', 'Facebook'), ('google', 'Google'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce'), ('mybasket', 'MyBasket')], default='shopify', max_length=15),
        ),
    ]
