# Generated by Django 3.2.13 on 2022-06-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0093_auto_20220331_1659'),
        ('supplements', '0093_auto_20220621_0914'),
    ]

    operations = [
    ]
