# Generated by Django 3.2.13 on 2022-06-30 07:15

from django.db import migrations
from app import settings
from supplements.models import PLSupplement, ShipStationAccount


def forward_func(apps, schema_editor):
    account = apps.get_model('supplements', 'ShipStationAccount')
    if settings.SHIPSTATION_API_KEY:
        account.objects.create(name='Dropified', api_key=settings.SHIPSTATION_API_KEY,
                               api_secret=settings.SHIPSTATION_API_SECRET)
        ship_acc = ShipStationAccount.objects.filter(name='Dropified').first()
        for pl_supplement in PLSupplement.objects.all():
            pl_supplement.shipstation_account = ship_acc
            pl_supplement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0094_merge_0093_auto_20220331_1659_0093_auto_20220621_0914'),
    ]

    operations = [
        migrations.RunPython(forward_func, migrations.RunPython.noop)
    ]
