# Generated by Django 3.2.14 on 2022-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0096_auto_20220704_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipstationaccount',
            name='store_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
