# Generated by Django 3.2.14 on 2022-08-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0097_shipstationaccount_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupplementlabel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('awaiting', 'In Review'), ('rejected', 'Rejected'),
                                            ('qapassed', 'QA Passed')], default='draft', max_length=8),
        ),
    ]
