# Generated by Django 3.2.14 on 2022-09-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplements', '0098_alter_usersupplementlabel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLSReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quality_rating', models.PositiveSmallIntegerField()),
                ('label_quality_rating', models.PositiveSmallIntegerField()),
                ('delivery_rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pl_supplement', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='pl_review', to='supplements.plsupplement')),
                ('pls_order_line', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    to='supplements.plsorderline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
