# Generated by Django 3.2.14 on 2022-09-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0099_plsorderline_batch_number'),
        ('supplements', '0099_plsreview'),
    ]

    operations = [
    ]
