# Generated by Django 3.2.15 on 2022-10-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0100_merge_0099_plsorderline_batch_number_0099_plsreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsorder',
            name='authorize_net_customer_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plsorder',
            name='authorize_net_payment_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
