# Generated by Django 3.2.15 on 2022-10-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        PLSOrder = apps.get_model("supplements", "PLSOrder")
        db_alias = schema_editor.connection.alias
        orders = list(PLSOrder.objects.using(db_alias).all())
        for order in orders:
            order.authorize_net_customer_id = order.user.authorize_net_customer.customer_id
            order.authorize_net_payment_id = order.user.authorize_net_customer.payment_id
            order.save()

    dependencies = [
        ('supplements', '0101_auto_20221003_2048'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
