# Generated by Django 3.2.14 on 2022-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0101_auto_20221003_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='barcode_label',
            field=models.BooleanField(default=True),
        ),
    ]
