# Generated by Django 3.2.14 on 2022-11-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0102_plsupplement_barcode_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsupplement',
            name='order_number_on_label',
            field=models.BooleanField(default=True),
        ),
    ]
