# Generated by Django 3.2.14 on 2022-11-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0103_plsupplement_order_number_on_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupplement',
            name='sample_product',
            field=models.BooleanField(default=False),
        ),
    ]
