# Generated by Django 3.2.16 on 2022-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0104_usersupplement_sample_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipstationaccount',
            name='labels_only',
            field=models.BooleanField(default=False),
        ),
    ]
