# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product_common.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble')], default='shopify', max_length=7)),
                ('store_id', models.IntegerField()),
                ('store_order_id', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('stripe_transaction_id', models.CharField(max_length=50)),
                ('shipstation_key', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('shipped', 'Shipped')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, product_common.mixins.OrderMixin),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble')], default='shopify', max_length=7)),
                ('store_id', models.IntegerField()),
                ('store_order_id', models.CharField(max_length=50)),
                ('line_id', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50)),
                ('shipstation_key', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product_common.Order')),
            ],
            bases=(models.Model, product_common.mixins.OrderLineMixin),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, product_common.mixins.PayoutMixin),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('tags', models.TextField()),
                ('shipstation_sku', models.CharField(blank=True, max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, product_common.mixins.ProductMixin),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('image_url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_common.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_items', to='product_common.Payout'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together=set([('store_type', 'store_id', 'store_order_id', 'line_id')]),
        ),
    ]
