# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0002_add_gkart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
