# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0004_order_is_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipstation_sku',
            field=models.CharField(max_length=20),
        ),
    ]
