# Generated by Django 2.2.12 on 2020-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0005_make_shipstation_sku_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce')], default='shopify', max_length=7),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce')], default='shopify', max_length=7),
        ),
    ]
