# Generated by Django 2.2.12 on 2020-04-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0005_make_shipstation_sku_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
