# Generated by Django 2.2.16 on 2020-11-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0008_auto_20201027_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
