# Generated by Django 2.2.16 on 2020-12-09 13:44

from django.db import migrations, models
import django.db.models.deletion
import product_common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0009_auto_20201125_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_shipping_supplier', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(product_common.mixins.SupplierMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='product_common.ProductSupplier'),
        ),
    ]
