# Generated by Django 2.2.16 on 2020-12-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0010_auto_20201209_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payout',
        ),
    ]
