# Generated by Django 2.2.24 on 2021-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0012_auto_20210114_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'),
                                            ('chq', 'CommerceHQ'),
                                            ('woo', 'WooCommerce'),
                                            ('ebay', 'eBay'),
                                            ('gear', 'GearBubble'),
                                            ('gkart', 'GrooveKart'),
                                            ('bigcommerce', 'BigCommerce'),
                                            ('mybasket', 'MyBasket')],
                                   default='shopify', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'),
                                            ('chq', 'CommerceHQ'),
                                            ('woo', 'WooCommerce'),
                                            ('ebay', 'eBay'),
                                            ('gear', 'GearBubble'),
                                            ('gkart', 'GrooveKart'),
                                            ('bigcommerce', 'BigCommerce'),
                                            ('mybasket', 'MyBasket')],
                                   default='shopify', max_length=15),
        ),
    ]
