# Generated by Django 2.2.24 on 2021-09-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0013_auto_20210810_1708'),
        ('product_common', '0013_auto_20210921_1535'),
    ]

    operations = [
    ]
