# Generated by Django 3.2.13 on 2022-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0016_auto_20220331_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
