image: python:2.7.11

services:
  - postgres:9.5.4
  - redis:3.0.3

before_script:
  - source ./scripts/prepare_build.sh
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
    - flake8
    - python manage.py test
    - python manage.py collectstatic --noinput --traceback 2>&1 | sed '/^Post-processed/d;/^Copying/d;/^$/d' | indent
    - python manage.py compress

  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - venv
