image: ubuntu:14.04

services:
  - postgres:9.4.9
  - redis:latest

before_script:
  - source ./scripts/prepare_build.sh
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
    - flake8
    - python manage.py test

  cache:
    paths:
      - venv