image: python:2.7

#cache:
#  paths:
#  - node_modules/

services:
  - postgres:9.4.5

test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  #- export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  - apt-get update -qy
  - apt-get install -y python-dev python-pip libmysqld-dev libssl-dev libffi-dev libxml2-dev libxslt1-dev
  - pip install -r requirements.txt
  - python manage.py test
