image: python:2.7

services:
  - postgres:9.4.5
  - redis:latest

before_script:
  - source ./scripts/prepare_build.sh
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
    - python manage.py test

  cache:
    paths:
      - venv