image: ubuntu:14.04

services:
  - postgres:9.5.4
  - redis:3.0.3

before_script:
  - source ./scripts/prepare_build.sh
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
    - flake8
    - python manage.py test

  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - venv
