version: '3'

services:
  db:
    image: postgres:9.5.12
    environment:
      POSTGRES_USER: postgres
  redis:
    image: redis:3.0
  celery:
    build: .
    container_name: dropified_celery
    command: >
      bash -c 'source .env; celery -A app.celery_base worker -Q celery,priority_high -O fair -l INFO';
    volumes:
      - .:/opt/dropified
    depends_on:
      - redis
  web:
    build: .
    container_name: dropified_web
    command: bash
    volumes:
      - .:/opt/dropified
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
