# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-12 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BigCommerceBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('config', models.CharField(blank=True, default='', max_length=512)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BigCommerceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, default='{}')),
                ('notes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('price', models.FloatField(blank=True, db_index=True, null=True)),
                ('tags', models.TextField(blank=True, db_index=True, default='')),
                ('product_type', models.CharField(db_index=True, max_length=300)),
                ('source_id', models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='BigCommerce Product ID')),
                ('source_slug', models.CharField(blank=True, default='', max_length=300)),
                ('config', models.TextField(blank=True, null=True)),
                ('variants_map', models.TextField(blank=True, default='')),
                ('supplier_map', models.TextField(blank=True, default='', null=True)),
                ('shipping_map', models.TextField(blank=True, default='', null=True)),
                ('bundle_map', models.TextField(blank=True, null=True)),
                ('mapping_config', models.TextField(blank=True, null=True)),
                ('monitor_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BigCommerce Product',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BigCommerceStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_index', models.IntegerField(default=0)),
                ('currency_format', models.CharField(blank=True, max_length=512, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('api_url', models.CharField(max_length=512)),
                ('api_key', models.CharField(max_length=300)),
                ('api_token', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('store_hash', models.CharField(default='', editable=False, max_length=50)),
                ('auto_fulfill', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BigCommerce Store',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BigCommerceSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(blank=True, max_length=512, null=True)),
                ('supplier_name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('supplier_url', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=512, null=True)),
                ('variants_map', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigcommerce_core.BigCommerceProduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='bigcommerce_core.BigCommerceStore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bigcommerceproduct',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigcommerce_core.BigCommerceSupplier'),
        ),
        migrations.AddField(
            model_name='bigcommerceproduct',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigcommerce_core.BigCommerceProduct', verbose_name='Dupliacte of product'),
        ),
        migrations.AddField(
            model_name='bigcommerceproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bigcommerce_core.BigCommerceStore'),
        ),
        migrations.AddField(
            model_name='bigcommerceproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bigcommerceboard',
            name='products',
            field=models.ManyToManyField(blank=True, to='bigcommerce_core.BigCommerceProduct'),
        ),
        migrations.AddField(
            model_name='bigcommerceboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
