# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('tip', models.CharField(blank=True, default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='GoalStepRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
            ],
            options={
                'verbose_name': 'goal step',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('show_me_how_url', models.URLField(blank=True, default='')),
                ('action_url', models.URLField(blank=True, default='')),
                ('action_title', models.CharField(blank=True, default='', max_length=100)),
                ('icon_src', models.CharField(blank=True, default='', max_length=200)),
                ('users', models.ManyToManyField(blank=True, related_name='completed_steps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoalRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goalsteprelationship',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Step'),
        ),
        migrations.AddField(
            model_name='goal',
            name='steps',
            field=models.ManyToManyField(blank=True, through='goals.GoalStepRelationship', to='goals.Step'),
        ),
        migrations.AddField(
            model_name='goal',
            name='users',
            field=models.ManyToManyField(blank=True, through='goals.UserGoalRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usergoalrelationship',
            unique_together=set([('user', 'goal')]),
        ),
        migrations.AlterUniqueTogether(
            name='goalsteprelationship',
            unique_together=set([('goal', 'step_number')]),
        ),
    ]
