# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from django.urls import reverse

from goals.step_slugs import ADD_PRODUCT_TO_BOARD


def forward(apps, schema_editor):
    Step = apps.get_model('goals', 'Step')
    url = f'{settings.APP_URL}{reverse("boards_list")}'
    Step.objects.filter(slug=ADD_PRODUCT_TO_BOARD).update(action_url=url)


def backward(apps, schema_editor):
    Step = apps.get_model('goals', 'Step')
    url = f'{settings.APP_URL}/{reverse("boards_list")}'
    Step.objects.filter(slug=ADD_PRODUCT_TO_BOARD).update(action_url=url)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20190324_1442'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
