# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_fix_step_3_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepExtraAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_url', models.URLField(blank=True, default='')),
                ('action_title', models.CharField(blank=True, default='', max_length=100)),
                ('icon_src', models.CharField(blank=True, default='', max_length=200)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_actions', to='goals.Step')),
            ],
        ),
    ]
