# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 07:07
from __future__ import unicode_literals

from django.db import migrations
from goals.step_slugs import SAVE_PRODUCT_TO_DROPIFIED


def add_data(apps, schema_editor):
    Step = apps.get_model('goals', 'Step')
    step = Step.objects.get(slug=SAVE_PRODUCT_TO_DROPIFIED)
    step.extra_actions.create(
        action_url='https://www.ebay.com/',
        action_title='GO TO EBAY',
        icon_src='/static/ebay-icon.png',
    )


def remove_data(apps, schema_editor):
    StepExtraAction = apps.get_model('goals', 'StepExtraAction')
    StepExtraAction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_add_extra_actions_model'),
    ]

    operations = [
        migrations.RunPython(add_data, remove_data),
    ]
