# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_add_extra_action_to_step2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoalrelationship',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
