# Generated by Django 2.2.16 on 2020-12-14 09:17

from django.db import migrations
from django.conf import settings
from django.templatetags.static import static
from django.urls import reverse

from goals.step_slugs import (
    ADD_PRODUCT_TO_BOARD,
    BOOK_COACHING_CALL,
)


def forwards_func(apps, schema_editor):
    Step = apps.get_model('goals', 'Step')

    step = Step.objects.get(slug=ADD_PRODUCT_TO_BOARD)
    step.title='Schedule your Free Coaching Call'
    step.description='Book a time and speak to our Success representatives to give your store the best chance of success.'
    step.slug=BOOK_COACHING_CALL
    step.action_title='BOOK MY CALL'
    step.action_url='https://calendly.com/dropified-customer-success/onboarding-walkthrough'
    step.icon_src=static('dropified-icon.png')
    step.show_me_how_url=""
    step.save()


def reverse_func(apps, schema_editor):
    Step = apps.get_model('goals', 'Step')

    step = Step.objects.get(slug=BOOK_COACHING_CALL)
    step.title='Add Your Product To A Board'
    step.description='Similar to Pinterest, you can save your products to Product Boards for organizing your research.'
    step.slug=ADD_PRODUCT_TO_BOARD
    step.action_title='GO TO PRODUCT BOARDS'
    step.action_url='{}/{}'.format(settings.APP_URL, reverse('boards_list'))
    step.icon_src=static('dropified-icon.png')
    step.show_me_how_url="https://www.dropified.com/training/using-dropified-software/create-dropified-boards-to-organize-selected-products/"
    step.save()


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_add_viewed_to_goals'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
