# Generated by Django 2.2.16 on 2020-12-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_add_viewed_to_goals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalsteprelationship',
            options={'ordering': ['step_number'], 'verbose_name': 'goal step'},
        ),
        migrations.AlterUniqueTogether(
            name='goalsteprelationship',
            unique_together=set(),
        ),
    ]
