import json

uk_provinces = {
"aberdare": "Mid Glamorgan",
"aberdeen": "Aberdeenshire",
"aberdovey": "Gwynedd",
"abergavenny": "Gwent",
"abergele": "Clwyd",
"abertillery": "Gwent",
"aberystwyth": "Dyfed",
"abingdon": "Oxfordshire",
"accrington": "Lancashire",
"airdrie": "Lanarkshire",
"alcester": "Warwickshire",
"aldeburgh": "Suffolk",
"alderley edge": "Cheshire",
"aldershot": "Hampshire",
"alfreton": "Derbyshire",
"alness": "Ross-shire",
"alnwick": "Northumberland",
"alresford": "Hampshire",
"alston": "Cumbria",
"alton": "Hampshire",
"altrincham": "Cheshire",
"ambleside": "Cumbria",
"amersham": "Buckinghamshire",
"amesbury": "Wiltshire",
"ammanford": "Carmarthenshire",
"andover": "Hampshire",
"anstruther": "Fife",
"antrim": "Co Antrim",
"appleby-in-westmorland": "Cumbria",
"arbroath": "Angus",
"ardrossan": "Ayrshire",
"armagh": "Co Armagh",
"arthog": "Gwynedd",
"arundel": "West Sussex",
"ascot": "Berkshire",
"ashbourne": "Derbyshire",
"ashburton": "Devon",
"ashford": "Middlesex",
"ashington": "Northumberland",
"ashtead": "Surrey",
"ashton-under-lyne": "Greater Manchester",
"attleborough": "Norfolk",
"aviemore": "Inverness-shire",
"axminster": "Devon",
"aylesbury": "Buckinghamshire",
"ayr": "Ayrshire",
"bala": "Gwynedd",
"baldock": "Hertfordshire",
"ballachulish": "Argyll",
"ballycastle": "Co Antrim",
"ballyclare": "Co Antrim",
"ballymena": "Co Antrim",
"ballymoney": "Co Antrim",
"bamburgh": "Northumberland",
"bamstaple": "Devon",
"banbridge": "Co Down",
"banbury": "Oxfordshire",
"banchory": "Kincardineshire",
"banff": "Aberdeenshire",
"bangor": "Gwynedd",
"banstead": "Surrey",
"barking": "Essex",
"barmouth": "Gwynedd",
"barnard castle": "Co Durham",
"barnet": "Hertfordshire",
"barnsley": "South Yorkshire",
"barnstaple": "Devon",
"barrow-in furness": "Cumbria",
"barry": "South Glamorgan",
"barton-upon-humber": "South Humberside",
"basildon": "Essex",
"basingstoke": "Hampshire",
"bath": "Avon",
"bathgate": "West Lothian",
"battle": "East Sussex",
"beaumaris": "Gwynedd",
"beccles": "Suffolk",
"beckenham": "Kent",
"bedale": "North Yorkshire",
"bedford": "Bedfordshire",
"belfast": "Belfast",
"belvedere": "Kent",
"benneet": "Essex",
"berkhamsted": "Hertfordshire",
"berwick-on-tweed": "Northumberland",
"betws-y-coed": "Conwy",
"beverley": "North Humberside",
"bewdley": "Worcestershire",
"bexhill-on-sea": "East Sussex",
"bicester": "Oxfordshire",
"bideford": "Devon",
"biggar": "Lanarkshire",
"biggleswade": "Bedfordshire",
"billericay": "Essex",
"billingshurst": "West Sussex",
"bingley": "West Yorkshire",
"birkenhead": "Merseyside",
"birmingham": "West Midlands",
"bishop auckland": "Co Durham",
"bishop's stortford": "Hertfordshire",
"bishops castle": "Shropshire",
"bishops waltham": "Hampshire",
"blackburn": "Lancashire",
"blackpool": "Lancashire",
"blaenau ffestiniog": "Gwynedd",
"blairgowrie": "Perthshire",
"blandford forum": "Dorset",
"blaydon-on-tyne": "Tyne and Wear",
"bodmin": "Cornwall",
"bognor regis": "West Sussex",
"boldon colliery": "Tyne and Wear",
"bolton": "Lancashire",
"bonnyrigg": "Midlothian",
"bootle": "Merseyside",
"bordon": "Hampshire",
"borehamwood": "Hertfordshire",
"boston": "Lincolnshire",
"botness": "West Lothian",
"bourne": "Lincolnshire",
"bournemouth": "Dorset",
"brackley": "Northamptonshire",
"bracknell": "Berkshire",
"bradford": "West Yorkshire",
"braintree": "Essex",
"brampton": "Cumbria",
"braunton": "Devon",
"brecon": "Powys",
"brentford": "Middlesex",
"brentwood": "Essex",
"bridgend": "Mid Glamorgan",
"bridgnorth": "Shropshire",
"bridgwater": "Somerset",
"bridlington": "North Humberside",
"bridport": "Dorset",
"brigg": "Lincolnshire",
"brighouse": "West Yorkshire",
"brighton": "East Sussex",
"bristol": "Avon",
"brixham": "Devon",
"broadford": "Isle of Skye",
"broadstairs": "Kent",
"broadway": "Hereford and Worcester",
"brockenhurst": "Hampshire",
"brodick": "Isle of Arran",
"bromley": "Kent",
"bromsgrove": "Hereford and Worcester",
"brooke": "Norfolk",
"broxburn": "West Lothian",
"buckfastleigh": "Devon",
"buckhurst hill": "Essex",
"buckie": "Banffshire",
"buckingham": "Buckinghamshire",
"bude": "Cornwall",
"budleigh salterton": "Devon",
"builth wells": "Powys",
"bunessan": "Isle of Mull",
"bungay": "Suffolk",
"burgess hill": "West Sussex",
"burnham-on-sea": "Somerset",
"burnley": "Lancashire",
"burton-on-trent": "Staffordshire",
"bury st edmunds": "Suffolk",
"bury": "Lancashire",
"bushmills": "Co Antrim",
"buxton": "Derbyshire",
"caernarvon": "Gwynedd",
"caerphilly": "Mid Glamorgan",
"calne": "Wiltshire",
"camberley": "Surrey",
"cambridge": "Cambridgeshire",
"camelford": "Cornwall",
"campbeltown": "Argyll",
"cannock": "Staffordshire",
"canterbury": "Kent",
"cardiff": "South Glamorgan",
"cardigan": "Dyfed",
"carlisle": "Cumbria",
"carloway": "Isle of Lewis",
"carluke": "Lanarkshire",
"carmarthen": "Dyfed",
"carnforth": "Lancashire",
"carrickfergus": "Co Antrim",
"carshalton": "Surrey",
"castle douglas": "Kirkcudbrightshire",
"castlederg": "Co Tyrone",
"castletown": "Isle of Man",
"castlewellan": "Co Down",
"caterham": "Surrey",
"cemmaes bay": "Gwynedd",
"cemmaes road": "Gwynedd",
"cerne abbas": "Dorset",
"chard": "Somerset",
"chatham": "Kent",
"chatteris": "Cambridgeshire",
"cheadle": "Cheshire",
"cheam": "Surrey",
"cheddar": "Somerset",
"chelmsford": "Essex",
"cheltenham": "Gloucestershire",
"chepstow": "Gwent",
"chertsey": "Surrey",
"chesham": "Buckinghamshire",
"chester": "Cheshire",
"chester-le-street": "Co Durham",
"chesterfield": "Derbyshire",
"chichester": "West Sussex",
"chippenham": "Wiltshire",
"chipping norton": "Oxfordshire",
"chipping sodbury": "Gloucestershire",
"chorley": "Lancashire",
"christchurch": "Dorset",
"church stretton": "Shropshire",
"cinderford": "Gloucestershne",
"cirencester": "Gloucestershire",
"clacton-on-sea": "Essex",
"cleethorpes": "South Humberside",
"clevedon": "Avon",
"clitheroe": "Lancashire",
"clogher": "Co Tyrone",
"clopton": "Northamptonshire",
"coalville": "Leicestershire",
"coatbridge": "Lanarkshire",
"cobham": "Surrey",
"cockermouth": "Cumbria",
"colchester": "Essex",
"coleraine": "Co Londonderry",
"coleshill": "Warwickshire",
"colwyn bay": "Clwyd",
"congleton": "Cheshire",
"coniston": "Cumbria",
"consett": "Co Durham",
"conwy": "Gwynedd",
"cookstown": "Co Tyrone",
"coppull": "Lancashire",
"corbridge": "Northumberland",
"corby": "Northamptonshire",
"corwen": "Clwyd",
"coulsdon": "Surrey",
"coventry": "West Midlands",
"craigavon": "Co Armagh",
"cramlington": "Northumberland",
"cranbrook": "Kent",
"cranleigh": "Surrey",
"craven arms": "Shropshire",
"crawley": "West Sussex",
"crediton": "Devon",
"crewe": "Cheshire",
"crieff": "Perthshire",
"cromer": "Norfolk",
"crowborough": "East Sussex",
"croy": "Inverness-shire",
"croydon": "Surrey",
"crumlin": "Co Antrim",
"cullompton": "Devon",
"cumnock": "East Ayrshire",
"cupar": "Fife",
"cwmbran": "Gwent",
"dagenham": "Essex",
"dalbeattie": "Kirkcudbrightshire",
"dalmally": "Argyll",
"dalry": "Ayrshire",
"darlington": "Co Durham",
"dartford": "Kent",
"darvel": "Ayrshire",
"daventry": "Northamptonshire",
"deal": "Kent",
"deeside": "Clwyd",
"derby": "Derbyshire",
"dereham": "Norfolk",
"devizes": "Wiltshire",
"dewsbury": "West Yorkshire",
"didcot": "Oxfordshire",
"dinas powis": "South Glamorgan",
"dingwall": "Ross-shire",
"diss": "Norfolk",
"dolgellau": "Gwynedd",
"doncaster": "South Yorkshire",
"dorchester": "Dorset",
"dorking": "Surrey",
"dornoch": "Sutherland",
"douglas": "Isle of Man",
"dover": "Kent",
"downham market": "Norfolk",
"downpatrick": "Co Down",
"driffield": "North Humberside",
"droitwich": "Hereford and Worcester",
"dromore": "Co Down",
"dudley": "West Midlands",
"dulverton": "Somerset",
"dumbarton": "Dunbartonshire",
"dumfries": "Dumfriesshire",
"dunbar": "East Lothian",
"dunblane": "Perthshire",
"dundee": "Angus",
"dunfermline": "Fife",
"dungannon": "Co Tyrone",
"dunkeld": "Perthshire",
"dunmow": "Essex",
"dunmurry": "Belfast",
"dunoon": "Argyll",
"duns": "Berwickshire",
"dunstable": "Bedfordshire",
"durham": "Co Durham",
"dursley": "Gloucestershire",
"easingwold": "North Yorkshire",
"east grinstead": "West Sussex",
"east kilbride": "South Lanarkshire",
"east molesey": "Surrey",
"eastbourne": "East Sussex",
"eastleigh": "Hampshire",
"ebbsfleet": "Kent",
"ebbw vale": "Gwent",
"edenbridge": "Kent",
"edgware": "Middlesex",
"edinburgh": "Edinburgh",
"egham": "Surrey",
"elgin": "Morayshire",
"ellesmere port": "Cheshire",
"ellon": "Aberdeenshire",
"ely": "Cambridgeshire",
"emsworth": "Hampshire",
"enfeld": "Middlesex",
"enniskillen": "Co Fermanagh",
"epping": "Essex",
"epsom": "Surrey",
"erith": "Kent",
"esher": "Surrey",
"evesham": "Worcestershire",
"exeter": "Devon",
"exmouth": "Devon",
"fakenham": "Norfolk",
"falkirk": "Stirlingshire",
"falmouth": "Cornwall",
"fareham": "Hampshire",
"faringdon": "Oxfordshire",
"farnborough": "Hampshire",
"farnham": "Surrey",
"felixstowe": "Suffolk",
"fishguard": "Dyfed",
"fivemiletown": "Co Tyrone",
"fleet": "Hampshire",
"fleetwood": "Lancashire",
"flint": "Clwyd",
"folkestone": "Kent",
"forfar": "Angus",
"fort william": "Inverness-shire",
"fortrose": "Ross-shire",
"fowey": "Cornwall",
"fraserburgh": "Aberdeenshire",
"freshwater": "Isle of Wight",
"frinton-on-sea": "Essex",
"frome": "Somerset",
"gainsborough": "Lincolnshire",
"gairloch": "Ross-shire",
"galasheils": "Selkirkshire",
"garstang": "Lancashire",
"gateshead": "Tyne and Wear",
"gerrards cross": "Buckinghamshire",
"gillingham": "Kent",
"girvan": "South Ayrshire",
"glamorgan": "Rotherham",
"glasgow": "Glasgow",
"glastonbury": "Somerset",
"glenrothes": "Fife",
"glossop": "Derbyshire",
"gloucester": "Gloucestershire",
"godalming": "Surrey",
"godstone": "Surrey",
"goole": "East Riding of Yorkshire",
"gosforth": "Cumbria",
"gosport": "Hampshire",
"grange-over-sands": "Cumbria",
"grangemouth": "Midlothian",
"grantham": "Lincolnshire",
"gravesend": "Kent",
"grays thurrock": "Essex",
"great dunmow": "Essex",
"great missenden": "Buckinghamshire",
"great yarmouth": "Norfolk",
"greenford": "Middlesex",
"greenock": "Renfrewshire",
"gretna": "Dumfriesshire",
"grimsby": "South Humberside",
"guernsey": "Channel Islands",
"guildford": "Surrey",
"guisborough": "North Yorkshire",
"guiseley": "West Yorkshire",
"gullane": "East Lothian",
"haddington": "East Lothian",
"hailsham": "East Sussex",
"halesowen": "West Midlands",
"halifax": "West Yorkshire",
"halstead": "Essex",
"haltwhistle": "Northumberland",
"hamilton": "Lanark shire",
"hampton": "Middlesex",
"harlow": "Essex",
"harpenden": "Hertfordshire",
"harrogate": "North Yorkshire",
"harrow": "Middlesex",
"hartlepool": "Cleveland",
"harwich": "Essex",
"haslemere": "Surrey",
"hassocks": "West Sussex",
"hastings": "East Sussex",
"hatfield": "Hertfordshire",
"hathersage": "Derbyshire",
"havant": "Hampshire",
"haverfordwest": "Pembrokeshire",
"haverhill": "Suffolk",
"hawick": "Roxburghshire",
"hawkshead": "Cumbria",
"hay-on-wye": "Powys",
"hayes": "Middlesex",
"hayling island": "Hampshire",
"haywards heath": "West Sussex",
"heanor": "Derbyshire",
"heathfield": "East Sussex",
"helensburgh": "Dunbartonshire",
"helmsley": "North Yorkshire",
"helston": "Cornwall",
"hemel hempstead": "Hertfordshire",
"henfield": "West Sussex",
"henley-on-thames": "Oxfordshire",
"hereford": "Hereford and Worcester",
"herne bay": "Kent",
"hertford": "Hertfordshire",
"hessle": "North Humberside",
"hexham": "Northumberland",
"heywood": "Lancashire",
"high wycombe": "Buckinghamshire",
"highbridge": "Somerset",
"hillsborough": "Co Down",
"hinckley": "Leicestershire",
"hindhead": "Surrey",
"hitchin": "Hertfordshire",
"hockley": "Essex",
"hoddesdon": "Hertfordshire",
"holbeach": "Lincolnshire",
"holmes chapel": "Cheshire",
"holsworthy": "Devon",
"holt": "Norfolk",
"holyhead": "Gwynedd",
"holywood": "Co Down",
"honington": "Lincolnshire",
"honiton": "Devon",
"hook": "Hampshire",
"horley": "Surrey",
"hornby": "Lancashire",
"hornchurch": "Essex",
"hornsea": "East Riding of Yorkshire",
"horsham": "West Sussex",
"houghton le spring": "Tyne and Wear",
"hounslow": "Middlesex",
"hove": "East Sussex",
"huddersfield": "West Yorkshire",
"hull": "North Humberside",
"hungerford": "Berkshire",
"hunstanton": "Norfolk",
"huntingdon": "Cambridgeshire",
"huntly": "Aberdeenshire",
"hyde": "Cheshire",
"hythe": "Kent",
"ilford": "Essex",
"ilfracombe": "Devon",
"ilkeston": "Derbyshire",
"ilkley": "West Yorkshire",
"immingham": "South Humberside",
"ingatestone": "Essex",
"insch": "Aberdeenshire",
"inveraray": "Argyll",
"inverness": "Inverness-shire",
"inverurie": "Aberdeenshire",
"iona": "Isle of Iona",
"ipstones": "Staffordshire",
"ipswich": "Suffolk",
"ironbridge": "Shropshire",
"isle of wight": "Isle of Wight",
"isleworth": "Middlesex",
"jersey": "Channel Islands",
"johnstone": "Renfrewshire",
"keighley": "West Yorkshire",
"kelso": "Roxburghshire",
"kendal": "Cumbria",
"kenilworth": "Warwickshire",
"keswick": "Cumbria",
"kettering": "Northamptonshire",
"kidderminster": "Hereford and Worcester",
"kilbirnie": "Ayrshire",
"killin": "Perthshire",
"killingholme": "Lincolnshire",
"kilmacolm": "Renfrewshire",
"kilmarnock": "Ayrshire",
"king's lynn": "Norfolk",
"kings langley": "Hertfordshire",
"kingsbridge": "Devon",
"kingston upon thames": "Surrey",
"kingswinford": "West Midlands",
"kington": "Herefordshire",
"kingussie": "Inverness-shire",
"kirkby stephen": "Cumbria",
"kirkcaldy": "Fife",
"kirkwhelpington": "Northumberland",
"kirriemuir": "Angus",
"knighton": "Powys",
"knutsford": "Cheshire",
"kyle": "Ross-shire",
"kyleakin": "Isle of Skye",
"laindon": "Essex",
"lairg": "Sutherland",
"lampeter": "Ceredigion",
"lanark": "Lanarkshire",
"lancaster": "Lancashire",
"lancing": "West Sussex",
"lapworth": "Warwickshire",
"larbert": "Stirlingshire",
"latheron": "Caithness",
"launceston": "Cornwall",
"leamington spa": "Warwickshire",
"leatherhead": "Surrey",
"ledbury": "Hereford and Worcester",
"leeds": "West Yorkshire",
"leicester": "Leicestershire",
"leigh": "Lancashire",
"leigh-on-sea": "Essex",
"leighton buzzard": "Bedfordshire",
"leiston": "Suffolk",
"leominster": "Hereford and Worcester",
"lerwick": "Isle of Shetland",
"letchworth": "Hertfordshire",
"lewes": "East Sussex",
"leyburn": "North Yorkshire",
"leyland": "Lancashire",
"lichfield": "Staffordshire",
"lightwater": "Surrey",
"limavady": "Co Londonderry",
"lincoln": "Lincolnshire",
"lingfield": "Surrey",
"liphook": "Hampshire",
"lisburn": "Co Antrim",
"liskeard": "Cornwall",
"liss": "Hampshire",
"littleborough": "Lancashire",
"littlehampton": "West Sussex",
"liverpool": "Merseyside",
"livingston": "West Lothian",
"llanarth": "Ceredigion",
"llanbedr": "Gwynedd",
"llandeilo": "Carmarthenshire",
"llandovery": "Carmarthenshire",
"llandrindod wells": "Powys",
"llandudno": "Gwynedd",
"llandysul": "Dyfed",
"llanelli": "Dyfed",
"llangollen": "Clwyd",
"llanidloes": "Powys",
"llanon": "Ceredigion",
"llanrwst": "Gwynedd",
"llantwit": "South Glamorgan",
"llanwrda": "Dyfed",
"llanwrtyd wells": "Powys",
"loanhead": "Midlothian",
"lochboisdale": "Isle of Uist",
"lochcarron": "Ross-shire",
"lochgilphead": "Argyll",
"lochwinnoch": "Renfrewshire",
"lockerbie": "Dumfriesshire",
"london": "London",
"londonderry": "Co Londonderry",
"loughborough": "Leicestershire",
"loughton": "Essex",
"louth": "Lincolnshire",
"lowestoft": "Suffolk",
"ludlow": "Shropshire",
"lurgan": "Co Antrim",
"luton": "Bedfordshire",
"lutterworth": "Leicestershire",
"lydney": "Gloucestershire",
"lymington": "Hampshire",
"lyndhurst": "Hampshire",
"lynton": "Devon",
"lytham stannes": "Lancashire",
"macclesfield": "Cheshire",
"machynlleth": "Powys",
"madingley": "Cambridgeshire",
"maesteg": "Mid Glamorgan",
"magharafelt": "Co Londonderry",
"maidenhead": "Berkshire",
"maidstone": "Kent",
"maldon": "Essex",
"malmesbury": "Wiltshire",
"malpas": "Cheshire",
"malton": "North Yorkshire",
"malvern": "Hereford and Worcester",
"manchester": "Greater Manchester",
"mansfield": "Nottinghamshire",
"march": "Cambridgeshire",
"margate": "Kent",
"market drayton": "Shropshire",
"market harborough": "Leicestershire",
"market rasen": "Lincolnshire",
"market weighton": "East Riding of Yorkshire",
"marlborough": "Wiltshire",
"marlow": "Buckinghamshire",
"martin": "Lincolnshire",
"maryport": "Cumbria",
"matlock": "Derbyshire",
"maud": "Aberdeenshire",
"medway": "Kent",
"meifod": "Powys",
"melksham": "Wiltshire",
"melton mowbray": "Leicestershire",
"mere": "Wiltshire",
"meriden": "West Midlands",
"merthyr tydfil": "Mid Glamorgan",
"mexborough": "South Yorkshire",
"middlesbrough": "Cleveland",
"middlewich": "Cheshire",
"midhurst": "West Sussex",
"mildenhall": "Suffolk",
"milford haven": "Pembrokeshire",
"milton keynes": "Buckinghamshire",
"minehead": "Somerset",
"mirfield": "West Yorkshire",
"mitcham": "Surrey",
"mitcheldean": "Gloucestershire",
"mold": "Clwyd",
"monmouth": "Gwent",
"montgomery": "Powys",
"montrose": "Angus",
"morden": "Surrey",
"morecambe": "Lancashire",
"moretonhampstead": "Devon",
"morpeth": "Northumberiand",
"moscow": "East Ayrshire",
"motherwell": "Lanarkshire",
"musselburgh": "Midlothian",
"nailsea": "Avon",
"nairn": "Inverness-shire",
"nantwich": "Cheshire",
"narberth": "Pembrokeshire",
"neath": "Neath Port Talbot",
"nefyn": "Gwynedd",
"nelson": "Lancashire",
"nethy bridge": "Inverness-shire",
"new malden": "Surrey",
"new mills": "Derbyshire",
"newark": "Nottinghamshire",
"newbury": "Berkshire",
"newcastle emlyn": "Dyfed",
"newcastle upon tyne": "Tyne and Wear",
"newcastle": "Staffordshire",
"newcastleton": "Roxburghshire",
"newent": "Gloucestershire",
"newhaven": "East Sussex",
"newmarket": "Suffolk",
"newport pagnell": "Buckinghamshire",
"newport": "Shropshire",
"newquay": "Cornwall",
"newton abbot": "Devon",
"newtown": "Powys",
"newtown-le- willows": "Merseyside",
"newtownabbey": "Co Antrim",
"newtownards": "Co Down",
"north berwick": "East Lothian",
"north shields": "Tyne and Wear",
"north walsham": "Norfolk",
"northallerton": "North Yorkshire",
"northampton": "Northamptonshire",
"northwich": "Cheshire",
"northwood": "Middlesex",
"norwich": "Norfolk",
"nottingham": "Nottinghamshire",
"nottinghamshire": "Nottinghamshire",
"nuneaton": "Warwickshire",
"oakham": "Leicestershire",
"oban": "Argyll",
"okehampton": "Devon",
"oldham": "Lancashire",
"omagh": "Co Tyrone",
"ongar": "Essex",
"ormskirk": "Lancashire",
"orpington": "Kent",
"ossett": "West Yorkshire",
"oswestry": "Shropshire",
"otley": "West Yorkshire",
"oxford": "Oxfordshire",
"oxted": "Surrey",
"paignton": "Devon",
"paisley": "Renfrewshire",
"pakenham": "Suffolk",
"par": "Cornwall",
"pembroke": "Dyfed",
"penarth": "South Glamorgan",
"pencombe": "Herefordshire",
"penicuik": "Midlothian",
"penmaenmawr": "Gwynedd",
"penrhyndeudraeth": "Gwynedd",
"penrith": "Cumbria",
"penryn": "Cornwall",
"penzance": "Cornwall",
"pershore": "Hereford and Worcester",
"perth": "Perthshire",
"peterborough": "Cambridgeshire",
"peterhead": "Aberdeenshire",
"petersfield": "Hampshire",
"petworth": "West Sussex",
"pevensey": "East Sussex",
"pewsey": "Wiltshire",
"pickering": "North Yorkshire",
"pinner": "Middlesex",
"pitlochry": "Perthshire",
"plymouth": "Devon",
"pocklington": "East Riding of Yorkshire",
"pontefract": "West Yorkshire",
"pontyclun": "Mid Glamorgan",
"pontypool": "Torfaen",
"pontypridd": "Mid Glamorgan",
"poole": "Dorset",
"pooley bridge": "Cumbria",
"port isaac": "Cornwall",
"port talbot": "West Glamorgan",
"porthcawl": "Mid Glamorgan",
"porthmadog": "Gwynedd",
"portree": "Isle of Skye",
"portrush": "Co Antrim",
"portsmouth": "Hampshire",
"potters bar": "Hertfordshire",
"poulton-le-fylde": "Lancashire",
"prescot": "Merseyside",
"prestatyn": "Clwyd",
"preston": "Lancashire",
"prestwick": "Ayrshire",
"princes risborough": "Buckinghamshire",
"prudhoe": "Northumberland",
"pulborough": "West Sussex",
"purley": "Surrey",
"pwllheli": "Gwynedd",
"radlett": "Hertfordshire",
"ramsey": "Isle of Man",
"ramsgate": "Kent",
"raughton head": "Cumbria",
"rayleigh": "Essex",
"reading": "Berkshire",
"redcar": "Cleveland",
"redditch": "Worcestershire",
"redhill": "Surrey",
"redruth": "Cornwall",
"reigate": "Surrey",
"retford": "Nottmghamshire",
"rhyl": "Clwyd",
"richmond": "Surrey",
"rickmansworth": "Hertfordshire",
"riding mill": "Northumberland",
"ringwood": "Hampshire",
"ripley": "Derbyshire",
"ripon": "North Yorkshire",
"robertsbridge": "East Sussex",
"rochdale": "Lancashire",
"rochester": "Kent",
"rochford": "Essex",
"rockbourne": "Hampshire",
"romford": "Essex",
"romsey": "Hampshire",
"ross-on-wye": "Herefordshire",
"rossendale": "Lancashire",
"rothbury": "Northumberland",
"rotherham": "South Yorkshire",
"rothesay": "Isle ofBute",
"royston": "Hertfordshire",
"rugby": "Warwickshire",
"rugeley": "Staffordshire",
"ruislip": "Middlesex",
"runcorn": "Cheshire",
"rushden": "Northamptonshire",
"ruthin": "Clwyd",
"rye": "East Sussex",
"ryton": "Tyne and Wear",
"saffron walden": "Essex",
"salford": "Lancashire",
"salisbury": "Wiltshire",
"saltash": "Cornwall",
"saltburn-by-the-sea": "Cleveland",
"saltcoats": "Ayrshire",
"sandbach": "Cheshire",
"sandhurst": "Berkshire",
"sandown": "Isle of Wight",
"sandwich": "Kent",
"sandy": "Bedfordshire",
"sanquhar": "Dumfriesshire",
"sawbridgeworth": "Hertfordshire",
"saxmundham": "Suffolk",
"scarborough": "North Yorkshire",
"scarinish": "Isle of Tiree",
"scunthorpe": "South Humberside",
"seaford": "East Sussex",
"seaham": "Co Durham",
"seahouses": "Northumberland",
"seaton": "Devon",
"sedbergh": "Cumbria",
"sedgefield": "Co Durham",
"selby": "North Yorkshire",
"selkirk": "Selkirkshire",
"settle": "North Yorkshire",
"sevenoaks": "Kent",
"shaftesbury": "Wiltshire",
"shap": "Cumbria",
"shawbost": "Isle of Lewis",
"sheffield": "South Yorkshire",
"shepperton": "Middlesex",
"shepton mallet": "Somerset",
"sherborne": "Dorset",
"sheringham": "Norfolk",
"shetland": "Isle of Shetland",
"shifnal": "Shropshire",
"shipley": "West Yorkshire",
"shrewsbury": "Shropshire",
"sidcup": "Kent",
"sidmouth": "Devon",
"sittingbourne": "Kent",
"skegness": "Lincolnshire",
"skelmersdale": "Lancashire",
"skipton": "North Yorkshire",
"sleaford": "Lincolnshire",
"slough": "Berkshire",
"solihull": "West Midlands",
"south croydon": "Surrey",
"south molton": "Devon",
"south petherton": "Somerset",
"south queensferry": "West Lothian",
"south wirral": "Merseyside",
"southall": "Middlesex",
"southam": "Warwickshire",
"southampton": "Hampshire",
"southend-on-sea": "Essex",
"southminster": "Essex",
"southport": "Merseyside",
"southsea": "Hampshire",
"southwell": "Nottinghamshire",
"sowerby": "North Yorkshire",
"spalding": "Lincolnshire",
"spilsby": "Lincolnshire",
"st albans": "Hertfordshire",
"st andrews": "Fife",
"st asaph": "Clwyd",
"st austell": "Cornwall",
"st clears": "Carmarthenshire",
"st helens": "Merseyside",
"st ives": "Cornwall",
"st leonards-on-sea": "East Sussex",
"stafford": "Staffordshire",
"staines": "Middlesex",
"stamford": "Lincolnshire",
"stanford-le-hope": "Essex",
"stanmore": "Middlesex",
"stevenage": "Hertfordshire",
"stirling": "Stirlingshire",
"stockport": "Cheshire",
"stocksfield": "Northumberland",
"stockton-on-tees": "Cleveland",
"stoke-on-trent": "Staffordshire",
"stone": "Staffordshire",
"stonehaven": "Kincardineshire",
"stornoway": "Isle of Lewis",
"stourbridge": "West Midlands",
"stourport-on-severn": "Hereford and Worcester",
"stow-on-the-wold": "Gloucestershire",
"stowmarket": "Suffolk",
"stranraer": "Wigtownshire",
"stratford-upon-avon": "Warwickshire",
"strathaven": "South Lanarkshire",
"strathcarron": "Ross-shire",
"strathpeffer": "Ross-shire",
"street": "Somerset",
"stroud": "Gloucestershire",
"sudbury": "Suffolk",
"sunbury-on-thames": "Middlesex",
"sunderland": "Tyne and Wear",
"surbiton": "Surrey",
"sutton coldfield": "West Midlands",
"sutton": "Surrey",
"sutton-in-ashfield": "Nottinghamshire",
"swaffham": "Norfolk",
"swanage": "Dorset",
"swanley": "Kent",
"swansea": "West Glamorgan",
"swindon": "Wiltshire",
"tain": "Ross-shire",
"talybont": "Gwynedd",
"tamworth": "Staffordshire",
"tarbert": "Argyll",
"tarporley": "Cheshire",
"taunton": "Somerset",
"tavistock": "Devon",
"teddington": "Middlesex",
"teignmouth": "Devon",
"telford": "Shropshire",
"temple cloud": "Somerset",
"templecombe": "Somerset",
"tenby": "Dyfed",
"tewkesbury": "Gloucestershire",
"thame": "Oxfordshire",
"thanet": "Kent",
"thatcham": "Berkshire",
"thetford": "Norfolk",
"thirsk": "North Yorkshire",
"thornton heath": "Surrey",
"thurso": "Caithness",
"tilbury": "Essex",
"tipton": "West Midlands",
"tiverton": "Devon",
"tonbridge": "Kent",
"torquay": "Devon",
"torrington": "Devon",
"totland bay": "Isle of Wight",
"towcester": "Northamptonshire",
"tranent": "East Lothian",
"tredegar": "Gwent",
"tring": "Hertfordshire",
"trowbridge": "Wiltshire",
"truro": "Cornwall",
"tunbridge wells": "Kent",
"turriff": "Aberdeenshire",
"twickenham": "Middlesex",
"tywyn": "Gwynedd",
"uckfield": "East Sussex",
"ulverston": "Cumbria",
"umberleigh": "Devon",
"uttoxeter": "Staffordshire",
"uxbridge": "Middlesex",
"ventnor": "Isle ofWight",
"wadebridge": "Cornwall",
"wakefield": "West Yorkshire",
"wallasey": "Merseyside",
"wallingford": "Oxfordshire",
"wallington": "Surrey",
"walsall": "West Midlands",
"walsingham": "Norfolk",
"waltham cross": "Hertfordshire",
"walton on the naze": "Essex",
"walton-on-thames": "Surrey",
"wantage": "Oxfordshire",
"warboys": "Cambridgeshire",
"ware": "Hertfordshire",
"wareham": "Dorset",
"warley": "West Midlands",
"warminster": "Wiltshire",
"warrington": "Cheshire",
"warwick": "Warwickshire",
"warwickshire": "Warwickshire",
"washington": "Tyne and Wear",
"watchet": "Somerset",
"watford": "Hertfordshire",
"wedmore": "Somerset",
"welling": "Kent",
"wellingborough": "Northamptonshire",
"wells": "Somerset",
"wells-next-the-sea": "Norfolk",
"welshpool": "Powys",
"welwyn garden city": "Hertfordshire",
"welwyn": "Hertfordshire",
"wem": "Shropshire",
"wembley": "Middlesex",
"west bromwich": "West Midlands",
"west byfleet": "Surrey",
"west drayton": "Middlesex",
"west heslerton": "North Yorkshire",
"west kilbride": "Ayrshire",
"west linton": "Peeblesshire",
"west malling": "Kent",
"west wickham": "Kent",
"westbury": "Wiltshire",
"westcliff-on-sea": "Essex",
"westerham": "Kent",
"weston-super-mare": "Avon",
"wetherby": "West Yorkshire",
"weybridge": "Surrey",
"weymouth": "Dorset",
"whatton": "Nottinghamshire",
"whitby": "North Yorkshire",
"whitchurch": "Shropshire",
"whitehaven": "Cumbria",
"whitland": "Dyfed",
"whitley bay": "Tyne and Wear",
"whitstable": "Kent",
"wick": "Caithness",
"wickford": "Essex",
"wigan": "Lancashire",
"wigton": "Cumbria",
"wilmslow": "Cheshire",
"wimborne": "Dorset",
"wincanton": "Somerset",
"winchester": "Hampshire",
"windermere": "Cumbria",
"windsor": "Berkshire",
"winscombe": "Somerset",
"wirral": "Merseyside",
"wisbech": "Cambridgeshire",
"wishaw": "Lanarkshire",
"witham": "Essex",
"witney": "Oxfordshire",
"woking": "Surrey",
"wokingham": "Berkshire",
"wolverhampton": "West Midlands",
"woodford green": "Essex",
"worcester": "Hereford and Worcester",
"workington": "Cumbria",
"worksop": "Nottinghamshire",
"wormbridge": "Herefordshire",
"worthing": "West Sussex",
"wotton-under-edge": "Gloucestershire",
"wrexham": "Clwyd",
"wymondham": "Norfolk",
"yateley": "Surrey",
"yelverton": "Devon",
"yeovil": "Somerset",
"york": "North Yorkshire",
}
