# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_common.Order')),
            ],
            options={
                'abstract': False,
            },
            bases=('product_common.order',),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('orderline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_common.OrderLine')),
            ],
            options={
                'abstract': False,
            },
            bases=('product_common.orderline',),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('payout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_common.Payout')),
            ],
            bases=('product_common.payout',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_common.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('product_common.product',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('productimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_common.ProductImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('product_common.productimage',),
        ),
    ]
