# Generated by Django 2.2.27 on 2022-04-11 15:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplements', '0090_auto_20220218_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBMarketplaceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('product_type', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('boards_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('data', models.TextField(blank=True, default='{}', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('config', models.TextField(blank=True, null=True)),
                ('variants_map', models.TextField(blank=True, default='')),
                ('supplier_map', models.TextField(blank=True, default='', null=True)),
                ('shipping_map', models.TextField(blank=True, default='', null=True)),
                ('bundle_map', models.TextField(blank=True, null=True)),
                ('mapping_config', models.TextField(blank=True, null=True)),
                ('monitor_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Facebook Marketplace Product ID')),
            ],
            options={
                'verbose_name': 'Facebook Marketplace Product',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FBMarketplaceStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_index', models.IntegerField(default=0)),
                ('currency_format', models.CharField(blank=True, max_length=512, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uninstall_reason', models.TextField(blank=True, null=True)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
                ('delete_request_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Marketplace Store',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FBMarketplaceUserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=512, verbose_name='Upload file URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_marketplace_core.FBMarketplaceProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FBMarketplaceSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(blank=True, max_length=512, null=True)),
                ('supplier_name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('supplier_url', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=512, null=True)),
                ('variants_map', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_marketplace_core.FBMarketplaceProduct')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='fb_marketplace_core.FBMarketplaceStore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fbmarketplaceproduct',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fb_marketplace_core.FBMarketplaceSupplier'),
        ),
        migrations.AddField(
            model_name='fbmarketplaceproduct',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fb_marketplace_core.FBMarketplaceProduct', verbose_name='Duplicate of product'),
        ),
        migrations.AddField(
            model_name='fbmarketplaceproduct',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fb_marketplace_core.FBMarketplaceStore'),
        ),
        migrations.AddField(
            model_name='fbmarketplaceproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbmarketplaceproduct',
            name='user_supplement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplements.UserSupplement'),
        ),
        migrations.CreateModel(
            name='FBMarketplaceBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('config', models.CharField(blank=True, default='', max_length=512)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('products', models.ManyToManyField(blank=True, to='fb_marketplace_core.FBMarketplaceProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FBMarketplaceOrderTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('line_id', models.BigIntegerField()),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=512, verbose_name='Source Order ID')),
                ('source_status', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Order Status')),
                ('source_tracking', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Tracking Number')),
                ('source_status_details', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Status Details')),
                ('source_type', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Type')),
                ('hidden', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False, verbose_name='User viewed the changes')),
                ('auto_fulfilled', models.BooleanField(default=False, verbose_name='Automatically fulfilled')),
                ('check_count', models.IntegerField(default=0)),
                ('data', models.TextField(blank=True, default='')),
                ('errors', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('status_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Status Update')),
                ('product_id', models.BigIntegerField()),
                ('fb_marketplace_status', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Facebook Marketplace Fulfillment Status')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_marketplace_core.FBMarketplaceStore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'index_together': {('store', 'order_id', 'line_id')},
            },
        ),
    ]
