# Generated by Django 3.2.14 on 2022-09-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multichannel_products_core', '0005_alter_producttemplate_created_at'),
        ('fb_marketplace_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbmarketplaceproduct',
            name='master_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multichannel_products_core.masterproduct'),  # noqa
        ),
        migrations.AddField(
            model_name='fbmarketplaceproduct',
            name='master_variants_map',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
