# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_alerts', '0003_auto_20180119_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantpricehistory',
            name='chq_product',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercehq_core.CommerceHQProduct'),
        ),
        migrations.AlterField(
            model_name='productvariantpricehistory',
            name='shopify_product',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadgalaxy.ShopifyProduct'),
        ),
        migrations.AlterField(
            model_name='productvariantpricehistory',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
