# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_alerts', '0005_auto_20190421_0231'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='productvariantpricehistory',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='productvariantpricehistory',
            name='chq_product',
        ),
        migrations.RemoveField(
            model_name='productvariantpricehistory',
            name='gkart_product',
        ),
        migrations.RemoveField(
            model_name='productvariantpricehistory',
            name='shopify_product',
        ),
        migrations.RemoveField(
            model_name='productvariantpricehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductVariantPriceHistory',
        ),
    ]
