# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_core', '0015_auto_20190725_2050'),
        ('product_alerts', '0006_auto_20190526_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchange',
            name='woo_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='woocommerce_core.WooProduct'),
        ),
    ]
