# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigcommerce_core', '0003_bigcommerceuserupload'),
        ('product_alerts', '0007_productchange_woo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchange',
            name='bigcommerce_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigcommerce_core.BigCommerceProduct'),
        ),
    ]
