# Generated by Django 2.2.24 on 2021-11-15 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_alerts', '0008_productchange_bigcommerce_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchange',
            name='bigcommerce_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bigcommerce_core.BigCommerceProduct'),
        ),
        migrations.AlterField(
            model_name='productchange',
            name='chq_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercehq_core.CommerceHQProduct'),
        ),
        migrations.AlterField(
            model_name='productchange',
            name='gkart_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groovekart_core.GrooveKartProduct'),
        ),
        migrations.AlterField(
            model_name='productchange',
            name='shopify_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadgalaxy.ShopifyProduct'),
        ),
        migrations.AlterField(
            model_name='productchange',
            name='woo_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woocommerce_core.WooProduct'),
        ),
    ]
