# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-07 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('layerapp', 'LayerApp')], default='layerapp', max_length=50)),
                ('source_id', models.IntegerField()),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('default_image', models.CharField(blank=True, default='', max_length=512)),
                ('source_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('user_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('source_type', models.CharField(choices=[('layerapp', 'LayerApp')], default='layerapp', max_length=50)),
                ('source_id', models.IntegerField(default=0)),
                ('source_data', models.TextField(default='{}')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prints.Category')),
            ],
        ),
    ]
