# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-20 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('product_type', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.TextField(blank=True, default='')),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('compare_at', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('ships_from', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('variants_images', models.TextField(default='{}')),
                ('variants_info', models.TextField(default='{}')),
                ('variants_sku', models.TextField(default='{}')),
                ('variants', models.TextField(default='[]')),
                ('images', models.TextField(default='[]')),
                ('extra_data', models.TextField(default='{}')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prints.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
