# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-07 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prints', '0002_customproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order_name', models.CharField(blank=True, default='', max_length=200)),
                ('tracking_company', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('stripe_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_url', models.TextField(default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('total_source_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_user_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('order_id', models.BigIntegerField()),
                ('order_reference', models.CharField(max_length=200)),
                ('customer_name', models.TextField(blank=True, default='')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('address1', models.TextField()),
                ('address2', models.TextField(default='', null=True)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=32)),
                ('source_type', models.CharField(choices=[('layerapp', 'LayerApp')], default='layerapp', max_length=50)),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting Payment'), ('pending_shipment', 'Awaiting Shipment'), ('shipped', 'Shipped'), ('pending_return', 'Awaiting Return'), ('returned', 'Returned')], default='pending_payment', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('line_id', models.BigIntegerField()),
                ('order_data_id', models.CharField(max_length=100)),
                ('title', models.TextField(default='')),
                ('product_id', models.BigIntegerField()),
                ('source_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('user_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('source_sku', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('custom_data', models.TextField(default='{}')),
                ('custom_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prints.CustomProduct')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='prints.Order')),
                ('track_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='order',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
