# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='source_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_price',
        ),
        migrations.AddField(
            model_name='product',
            name='source_prices',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_prices',
            field=models.TextField(default='{}'),
        ),
    ]
