# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-13 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0004_auto_20191111_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payout Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='source_paid_reference',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Payout Reference'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_source_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_user_price',
        ),
    ]
