# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-17 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0005_order_source_paid_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customproduct',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='product',
            name='dropified_image',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Default Image (Overrite)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
