# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0006_auto_20191117_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('dropified_profit', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Dropified Profit')),
                ('source_profit', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='LayerApp Profit')),
                ('target', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='User Price')),
                ('retail', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Retail Price (MSRP)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Product Cost')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='source_prices',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_prices',
        ),
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='skus',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_paid_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Payout Reference'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prints.Product'),
        ),
    ]
