# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0007_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
