# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-18 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0009_auto_20191205_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user_price',
            new_name='dropified_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dropified_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='source_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
