version: '3'

services:
  db:
    image: postgres:9.5.12
    environment:
      POSTGRES_USER: postgres
  redis:
    image: redis:6.0-alpine
  celery:
    build: ..
    container_name: dropified_celery
    command: >
      bash -c 'source .env; celery -A app.celery_base worker -Q celery,priority_high -O fair -l INFO';
    volumes:
      - ..:/opt/dropified
    depends_on:
      - redis
  web:
    build: ..
    container_name: dropified_web
    command: >
      bash -c 'source .env; ./manage.py runserver 0.0.0.0:8000';
    volumes:
      - ..:/opt/dropified
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
  nginx:
    image: nginx
    container_name: dropified_nginx
    volumes:
      - ../app/config/nginx/docker.dropified.com:/etc/nginx/nginx.conf:ro
    ports:
      - "9080:80"
    depends_on:
      - web
