# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 16:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAutomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('first_step', models.IntegerField(default=0)),
                ('last_step', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_automations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwilioLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, default='', max_length=50)),
                ('from_number', models.CharField(blank=True, default='', max_length=50)),
                ('call_duration', models.IntegerField(default=0, null=True)),
                ('call_sid', models.CharField(blank=True, default='', max_length=50)),
                ('call_status', models.CharField(blank=True, default='', max_length=50)),
                ('log_type', models.CharField(blank=True, default='', max_length=50)),
                ('digits', models.CharField(blank=True, default='', max_length=50)),
                ('twilio_metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TwilioPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_number', models.CharField(blank=True, default='', max_length=50)),
                ('forwarding_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Incoming calls allowed'), ('inactive', 'Forwardning all incoming calls')], default='', max_length=50)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('twilio_sid', models.CharField(blank=True, default='', max_length=50)),
                ('twilio_metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('automation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='phone_automation.TwilioAutomation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_phone_number', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwilioRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_sid', models.CharField(blank=True, default='', max_length=50)),
                ('recording_url', models.CharField(blank=True, default='', max_length=300)),
                ('twilio_metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('twilio_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_recordings', to='phone_automation.TwilioLog')),
            ],
        ),
        migrations.CreateModel(
            name='TwilioStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(max_length=100)),
                ('step', models.IntegerField(default=0, null=True)),
                ('next_step', models.IntegerField(default=0, null=True)),
                ('config', models.TextField(default='{}')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='phone_automation.TwilioAutomation')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='phone_automation.TwilioStep')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='TwilioUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=512, verbose_name='Upload file URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_automation.TwilioPhoneNumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
