# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_subscription', '0009_auto_20190609_1502'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phone_automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallflexCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_credits', models.BigIntegerField(default=0)),
                ('phone_type', models.CharField(choices=[('tollfree', 'Toll-Free Number'), ('local', 'Local Number')], default='tollfree', max_length=50)),
                ('stripe_invoice', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callflex_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CallflexCreditsPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_credits', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0, verbose_name='In USD')),
            ],
        ),
        migrations.CreateModel(
            name='TwilioAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='{}')),
                ('alert_event', models.CharField(choices=[('all_calls', 'All Calls'), ('new_callers', 'Only First Time Callers'), ('missed_calls', 'Only Missed Calls'), ('voicemails', 'Only Calls with Voicemails')], default='', max_length=50)),
                ('alert_type', models.CharField(choices=[('email', 'Email')], default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
        ),
        migrations.CreateModel(
            name='TwilioCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('timezone', models.CharField(default='', max_length=255)),
                ('config', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwilioSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(default='{}')),
                ('freq_daily', models.BooleanField(default=False)),
                ('freq_weekly', models.BooleanField(default=False)),
                ('freq_monthly', models.BooleanField(default=False)),
                ('include_calllogs', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_summaries', to='phone_automation.TwilioCompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_summaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='twiliophonenumber',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='twilioupload',
            name='phone',
        ),
        migrations.AddField(
            model_name='twilioautomation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AddField(
            model_name='twilioautomation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='twiliolog',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='twiliolog',
            name='phone_type',
            field=models.CharField(choices=[('tollfree', 'Toll-Free Number'), ('local', 'Local Number')], default='tollfree', max_length=50),
        ),
        migrations.AddField(
            model_name='twiliolog',
            name='twilio_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_logs', to='phone_automation.TwilioPhoneNumber'),
        ),
        migrations.AddField(
            model_name='twiliophonenumber',
            name='custom_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_phone_numbers', to='stripe_subscription.CustomStripeSubscription'),
        ),
        migrations.AddField(
            model_name='twiliophonenumber',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twiliophonenumber',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='twiliophonenumber',
            name='type',
            field=models.CharField(choices=[('tollfree', 'Toll-Free Number'), ('local', 'Local Number')], default='tollfree', max_length=50),
        ),
        migrations.AddField(
            model_name='twilioupload',
            name='automation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation', to='phone_automation.TwilioAutomation'),
        ),
        migrations.AlterField(
            model_name='twiliophonenumber',
            name='automation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phone_automation.TwilioAutomation'),
        ),
        migrations.AlterField(
            model_name='twiliophonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_phone_numbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twilioalert',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_alerts', to='phone_automation.TwilioCompany'),
        ),
        migrations.AddField(
            model_name='twilioalert',
            name='twilio_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_alerts', to='phone_automation.TwilioPhoneNumber'),
        ),
        migrations.AddField(
            model_name='twilioalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twiliophonenumber',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phone_automation.TwilioCompany'),
        ),
    ]
