# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_automation', '0002_auto_20190609_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilioupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
