# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_automation', '0004_callflexshopifyusagecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='callflexshopifyusagecharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Amount(in USD)'),
        ),
    ]
