# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-05 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_automation', '0005_callflexshopifyusagecharge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliolog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
