# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_automation', '0006_twiliolog_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliophonenumber',
            name='status',
            field=models.CharField(choices=[('active', 'Incoming calls allowed'), ('inactive', 'Forwardning all incoming calls'), ('released', 'Released')], default='', max_length=50),
        ),
    ]
