# Generated by Django 2.2.12 on 2020-06-12 16:04

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_automation', '0008_auto_20200513_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilioautomation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_automations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twiliophonenumber',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phone_automation.TwilioAutomation'),
        ),
        migrations.AlterField(
            model_name='twiliophonenumber',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phone_automation.TwilioCompany'),
        ),
        migrations.AlterField(
            model_name='twiliophonenumber',
            name='custom_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_phone_numbers', to='stripe_subscription.CustomStripeSubscription'),
        ),
        migrations.AlterField(
            model_name='twiliophonenumber',
            name='twilio_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
