# Generated by Django 3.2.4 on 2021-06-03 23:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_automation', '0009_auto_20200612_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliolog',
            name='twilio_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='twiliophonenumber',
            name='twilio_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='twiliorecording',
            name='twilio_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
