# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_article_show_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarlink',
            name='store_type',
            field=models.CharField(choices=[('default', 'All Stores'), ('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('bigcommerce', 'BigCommerce')], default='default', max_length=50),
        ),
    ]
