# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20191111_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarlink',
            name='store_type',
            field=models.CharField(choices=[('default', 'All Stores'), ('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce')], default='default', max_length=50),
        ),
    ]
