# Generated by Django 2.2.24 on 2021-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_auto_20210712_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarlink',
            name='store_type',
            field=models.CharField(choices=[('default', 'All Stores'),
                                            ('shopify', 'Shopify'),
                                            ('chq', 'CommerceHQ'),
                                            ('woo', 'WooCommerce'),
                                            ('gkart', 'GrooveKart'),
                                            ('bigcommerce', 'BigCommerce'),
                                            ('ebay', 'eBay')],
                                   default='default', max_length=50),
        ),
    ]
