# Generated by Django 2.2.25 on 2022-01-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_auto_20210921_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarlink',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarlink',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
