# Generated by Django 2.2.27 on 2022-02-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0033_auto_20220128_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarlink',
            name='store_type',
            field=models.CharField(choices=[('default', 'All Stores'), ('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce'), ('ebay', 'eBay'), ('fb', 'Facebook')], default='default', max_length=50),
        ),
    ]
