# Generated by Django 2.2.27 on 2022-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0034_auto_20220218_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarlink',
            name='store_type',
            field=models.CharField(choices=[('default', 'All Stores'), ('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce'), ('ebay', 'eBay'), ('fb', 'Facebook'), ('google', 'Google')], default='default', max_length=50),
        ),
    ]
