# Generated by Django 3.2.13 on 2022-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0242_userprofile_subuser_google_stores'),
        ('article', '0035_auto_20220331_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarlink',
            name='display_bundles',
            field=models.ManyToManyField(blank=True, to='leadgalaxy.FeatureBundle'),
        ),
    ]
