# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbubble_core', '0010_auto_20180719_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearbubblestore',
            name='mode',
            field=models.CharField(choices=[(b'staging', b'Staging'), (b'live', b'Live')], default=b'live', max_length=7),
        ),
    ]
