# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbubble_core', '0016_gearbubblestore_currency_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearbubbleboard',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
