# Generated by Django 3.2.14 on 2022-09-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearbubble_core', '0023_gearbubbleproduct_master_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearbubbleproduct',
            name='master_variants_map',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
