# Generated by Django 2.2.24 on 2021-06-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercehq_core', '0015_auto_20210626_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercehqproduct',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='commercehq_core.CommerceHQStore'),  # noqa
        ),
    ]
