# Generated by Django 2.2.24 on 2021-06-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercehq_core', '0017_auto_20210626_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercehqproduct',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
