# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrooveKartBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('config', models.CharField(blank=True, default='', max_length=512)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
            options={
                'verbose_name': 'GrooveKart Board',
                'verbose_name_plural': 'GrooveKart Boards',
            },
        ),
        migrations.CreateModel(
            name='GrooveKartOrderTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('line_id', models.BigIntegerField()),
                ('groovekart_status', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='GrooveKart Fulfillment Status')),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=512, verbose_name='Source Order ID')),
                ('source_status', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Order Status')),
                ('source_tracking', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Tracking Number')),
                ('source_status_details', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Status Details')),
                ('source_type', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Type')),
                ('hidden', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False, verbose_name='User viewed the changes')),
                ('auto_fulfilled', models.BooleanField(default=False, verbose_name='Automatically fulfilled')),
                ('check_count', models.IntegerField(default=0)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('status_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Status Update')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrooveKartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, default='{}')),
                ('notes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=300)),
                ('price', models.FloatField(blank=True, db_index=True, null=True)),
                ('tags', models.TextField(blank=True, db_index=True, default='')),
                ('product_type', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('source_id', models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='GrooveKartSupplier Product ID')),
                ('source_slug', models.CharField(blank=True, default='', max_length=300)),
                ('variants_map', models.TextField(blank=True, default='')),
                ('supplier_map', models.TextField(blank=True, default='', null=True)),
                ('shipping_map', models.TextField(blank=True, default='', null=True)),
                ('mapping_config', models.TextField(blank=True, null=True)),
                ('monitor_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GrooveKart Product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrooveKartStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('api_url', models.CharField(max_length=512)),
                ('api_key', models.CharField(max_length=300)),
                ('api_token', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('store_hash', models.CharField(default='', editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GrooveKart Store',
            },
        ),
        migrations.CreateModel(
            name='GrooveKartSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(blank=True, max_length=512, null=True)),
                ('supplier_name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('supplier_url', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=512, null=True)),
                ('variants_map', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groovekart_core.GrooveKartProduct')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='groovekart_core.GrooveKartStore')),
            ],
        ),
        migrations.AddField(
            model_name='groovekartproduct',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groovekart_core.GrooveKartSupplier'),
        ),
        migrations.AddField(
            model_name='groovekartproduct',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groovekart_core.GrooveKartProduct', verbose_name='Duplicate of product'),
        ),
        migrations.AddField(
            model_name='groovekartproduct',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='groovekart_core.GrooveKartStore'),
        ),
        migrations.AddField(
            model_name='groovekartproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groovekartordertrack',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groovekart_core.GrooveKartStore'),
        ),
        migrations.AddField(
            model_name='groovekartordertrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groovekartboard',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='boards', to='groovekart_core.GrooveKartProduct'),
        ),
        migrations.AddField(
            model_name='groovekartboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='groovekartordertrack',
            index_together=set([('store', 'order_id', 'line_id')]),
        ),
    ]
