# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groovekart_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groovekartproduct',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
