# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-31 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groovekart_core', '0006_groovekartstore_currency_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='groovekartproduct',
            name='bundle_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
