# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-11 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groovekart_core', '0009_groovekartordertrack_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='groovekartstore',
            name='is_one_and_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groovekartstore',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='groovekartstore',
            name='api_token',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='groovekartstore',
            name='api_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
