# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-06 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groovekart_core', '0010_one_and_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groovekartstore',
            old_name='is_one_and_done',
            new_name='is_lite',
        ),
    ]
