# Generated by Django 2.2.16 on 2020-11-10 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketOrderTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('line_id', models.BigIntegerField()),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=512, verbose_name='Source Order ID')),
                ('source_status', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Order Status')),
                ('source_tracking', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Tracking Number')),
                ('source_status_details', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Status Details')),
                ('source_type', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Type')),
                ('hidden', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False, verbose_name='User viewed the changes')),
                ('auto_fulfilled', models.BooleanField(default=False, verbose_name='Automatically fulfilled')),
                ('check_count', models.IntegerField(default=0)),
                ('data', models.TextField(blank=True, default='')),
                ('errors', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('status_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Status Update')),
                ('store', models.IntegerField(default=0)),
                ('product_id', models.BigIntegerField()),
                ('basket_order_status', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'index_together': {('store', 'order_id', 'line_id')},
            },
        ),
    ]
