# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_dashboard', '0013_auto_20180803_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccess',
            name='facebook_user_id',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
