# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_dashboard', '0014_facebookaccess_facebook_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccess',
            name='account_ids',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
