# Generated by Django 2.0.13 on 2020-02-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinginformationentryevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='planselectionevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='registrationevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='successfulpaymentevent',
            options={'base_manager_name': 'objects'},
        ),
    ]
