# Generated by Django 2.2.16 on 2020-12-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_events', '0004_storecreatedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementLabelForApprovalEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytic_events.Event')),
                ('product_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analytic_events.event',),
        ),
    ]
