# Generated by Django 2.2.23 on 2021-07-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment_fee', '0003_auto_20210108_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfeeconfig',
            name='fee_flat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Flat Sales per item (PLS orders only)'),
        ),
    ]
