# Generated by Django 2.2.24 on 2021-12-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment_fee', '0004_salesfeeconfig_fee_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfeeconfig',
            name='monthly_free_limit',
            field=models.IntegerField(blank=True, default='0', verbose_name='Apply fees only after this amount of orders (monthly)'),
        ),
    ]
