# Generated by Django 2.2.24 on 2022-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment_fee', '0005_salesfeeconfig_monthly_free_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfeeconfig',
            name='monthly_free_amount',
            field=models.IntegerField(blank=True, default='0', verbose_name='Apply fees when this total USD amount reached (monthly)'),
        ),
        migrations.AddField(
            model_name='salesfeeconfig',
            name='process_fees_trigger',
            field=models.CharField(choices=[('always', 'Always'), ('count', 'When orders count reached'),
                                            ('amount', 'When orders amount reached')], default='always', max_length=20,
                                   verbose_name='When to process fees'),
        ),
        migrations.AlterField(
            model_name='salesfeeconfig',
            name='monthly_free_limit',
            field=models.IntegerField(blank=True, default='0', verbose_name='Apply fees after this count of orders (monthly)'),
        ),
    ]
