# Generated by Django 2.2.24 on 2022-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment_fee', '0006_auto_20220106_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesfeeconfig',
            name='fee_flat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Flat Sales Fee(per item for PLS, but per order for non-PLS)'),
        ),
    ]
