# Generated by Django 2.2.24 on 2022-01-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0233_auto_20211203_1823'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmenuitem',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='applicationmenuitem',
            name='new_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationmenuitem',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='applications', to='leadgalaxy.GroupPlan'),
        ),
    ]
