# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliexpressFulfillmentCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_object_id', models.PositiveIntegerField()),
                ('order_id', models.BigIntegerField()),
                ('source_id', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateField(db_index=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('products_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('store_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_object_id', models.PositiveIntegerField()),
                ('access_token', models.CharField(max_length=255)),
                ('expires_in', models.DateTimeField(blank=True, default=None, null=True)),
                ('facebook_user_id', models.CharField(default='', max_length=100)),
                ('account_ids', models.TextField(blank=True, default='')),
                ('store_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync', models.DateField(null=True)),
                ('account_id', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('config', models.CharField(choices=[('include', 'Include Selected Campaign Only'), ('include_and_new', 'Include Selected Campaign and newer ones'), ('exclude', 'Exclude Selected Campaign')], default='selected', max_length=100)),
                ('campaigns', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='profits.FacebookAccess')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookAdCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(default='', max_length=100, null=True)),
                ('created_at', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='profits.FacebookAccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_object_id', models.PositiveIntegerField()),
                ('created_at', models.DateField()),
                ('order_ids', models.TextField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('store_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_object_id', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('store_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterIndexTogether(
            name='othercost',
            index_together=set([('store_content_type', 'store_object_id', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='orderrevenue',
            index_together=set([('store_content_type', 'store_object_id')]),
        ),
        migrations.AlterIndexTogether(
            name='facebookaccess',
            index_together=set([('store_content_type', 'store_object_id')]),
        ),
        migrations.AlterIndexTogether(
            name='aliexpressfulfillmentcost',
            index_together=set([('store_content_type', 'store_object_id', 'order_id', 'source_id')]),
        ),
    ]
