# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 18:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_object_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('order_id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('store_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RenameModel(
            old_name='AliexpressFulfillmentCost',
            new_name='FulfillmentCost',
        ),
        migrations.AlterModelOptions(
            name='orderrevenue',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='orderrevenue',
            old_name='revenue',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='orderrevenue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderrevenue',
            name='order_ids',
        ),
        migrations.AddField(
            model_name='orderrevenue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 18, 35, 56, 88261, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrevenue',
            name='order_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='orderrefund',
            index_together=set([('store_content_type', 'store_object_id')]),
        ),
    ]
