# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0002_auto_20190422_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrevenue',
            name='items',
            field=models.CharField(blank=True, max_length=255, null=True),
            preserve_default=False,
        ),
    ]
