# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 21:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0004_auto_20190422_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrevenue',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None),
        ),
    ]
