# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 16:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profits', '0006_orderrevenue_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('order_id', models.BigIntegerField()),
                ('order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('order_id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_object_id', models.PositiveIntegerField()),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('store_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='orderrefund',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='orderrefund',
            name='store_content_type',
        ),
        migrations.AlterIndexTogether(
            name='orderrevenue',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='orderrevenue',
            name='store_content_type',
        ),
        migrations.RemoveField(
            model_name='facebookaccess',
            name='account_ids',
        ),
        migrations.DeleteModel(
            name='OrderRefund',
        ),
        migrations.DeleteModel(
            name='OrderRevenue',
        ),
        migrations.AddField(
            model_name='profitrefund',
            name='sync',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='profits.ProfitSync'),
        ),
        migrations.AddField(
            model_name='profitorder',
            name='sync',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profits.ProfitSync'),
        ),
        migrations.AlterIndexTogether(
            name='profitsync',
            index_together=set([('store_content_type', 'store_object_id')]),
        ),
    ]
