# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0007_auto_20190423_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitorder',
            name='items',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
