# Generated by Django 2.2.24 on 2021-10-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliexpressaccount',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
