# Generated by Django 3.2.13 on 2022-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress_core', '0006_auto_20220303_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliexpressaccount',
            name='is_admitad',
            field=models.BooleanField(default=False),
        ),
    ]
