# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groovekart_core', '0003_groovekartuserupload'),
        ('product_feed', '0013_auto_20181128_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrooveKartFeedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Generated'), (2, 'Generating')], default=0)),
                ('feed_options', models.TextField(blank=True, null=True)),
                ('revision', models.IntegerField(default=0)),
                ('all_variants', models.BooleanField(default=True)),
                ('include_variants_id', models.BooleanField(default=True)),
                ('default_product_category', models.CharField(blank=True, default='', max_length=512)),
                ('generation_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('fb_access_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Facebook Access')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedstatus', to='groovekart_core.GrooveKartStore')),
            ],
            options={
                'verbose_name': 'GrooveKart Feed Status',
                'verbose_name_plural': 'GrooveKart Feed Statuses',
            },
        ),
    ]
