# Generated by Django 2.2.16 on 2021-03-15 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlibabaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(
                    choices=[
                        ('shopify', 'Shopify'),
                        ('chq', 'CommerceHQ'),
                        ('woo', 'WooCommerce'),
                        ('gear', 'GearBubble'),
                        ('gkart', 'GrooveKart'),
                        ('bigcommerce', 'BigCommerce')
                    ],
                    default='shopify',
                    max_length=15
                )),
                ('order_data_ids', models.TextField(blank=True, default='')),
                ('store_id', models.IntegerField()),
                ('store_order_id', models.CharField(blank=True, default='', max_length=30)),
                ('trade_id', models.CharField(blank=True, default='', max_length=30)),
                ('source_status', models.CharField(blank=True, default='unpay', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='ISO4217 Currency Code')),
                ('products_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlibabaOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, default='', max_length=30)),
                ('variant_id', models.CharField(blank=True, default='', max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_tracking', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Source Tracking Number')),
                ('store_line_id', models.CharField(blank=True, default='', max_length=30)),
                ('is_bundled', models.BooleanField(default=False)),
                ('order_track_id', models.BigIntegerField(blank=True, null=True)),
                ('combined_trade_ids', models.CharField(blank=True, default='', max_length=512)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alibaba_core.AlibabaOrder')),
            ],
        ),
        migrations.CreateModel(
            name='AlibabaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(default='')),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('alibaba_user_id', models.CharField(blank=True, default='', max_length=100)),
                ('alibaba_email', models.CharField(blank=True, default='', max_length=255)),
                ('ecology_token', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alibaba', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
