# Generated by Django 2.2.16 on 2021-03-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alibabaaccount',
            name='ecology_token_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
