# Generated by Django 2.2.18 on 2021-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba_core', '0002_alibabaaccount_ecology_token_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alibabaaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
