# Generated by Django 2.2.18 on 2021-08-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba_core', '0003_alibabaaccount_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alibabaorder',
            name='tracking_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
