# Generated by Django 2.2.24 on 2021-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba_core', '0004_alibabaorder_tracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alibabaorder',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'),
                                            ('chq', 'CommerceHQ'),
                                            ('woo', 'WooCommerce'),
                                            ('ebay', 'eBay'),
                                            ('gear', 'GearBubble'),
                                            ('gkart', 'GrooveKart'),
                                            ('bigcommerce', 'BigCommerce')],
                                   default='shopify', max_length=15),
        ),
    ]
