# Generated by Django 2.2.25 on 2022-01-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba_core', '0006_auto_20220103_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alibabaorder',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('ebay', 'eBay'), ('fb', 'Facebook'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce')], default='shopify', max_length=15),
        ),
    ]
