# Generated by Django 2.2.27 on 2022-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba_core', '0007_auto_20220114_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alibabaorder',
            name='store_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('chq', 'CommerceHQ'), ('woo', 'WooCommerce'), ('ebay', 'eBay'), ('fb', 'Facebook'), ('google', 'Google'), ('gear', 'GearBubble'), ('gkart', 'GrooveKart'), ('bigcommerce', 'BigCommerce')], default='shopify', max_length=15),
        ),
    ]
