# Generated by Django 2.2.24 on 2021-08-25 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suredone_core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplements', '0086_auto_20210526_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('product_type', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('data', models.TextField(blank=True, default='{}', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('config', models.TextField(blank=True, null=True)),
                ('variants_map', models.TextField(blank=True, default='')),
                ('supplier_map', models.TextField(blank=True, default='', null=True)),
                ('shipping_map', models.TextField(blank=True, default='', null=True)),
                ('bundle_map', models.TextField(blank=True, null=True)),
                ('mapping_config', models.TextField(blank=True, null=True)),
                ('monitor_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SureDone GUID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SureDone SKU')),
                ('product_description', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, default='New', max_length=255)),
                ('thumbnail_image', models.TextField(blank=True, null=True, verbose_name="Product's main thumbnail image")),
                ('media_links_data', models.TextField(blank=True, null=True, verbose_name="Product's media links in a JSON string")),
                ('ebay_product_id', models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='eBay Product ID')),
                ('ebay_store_index', models.BigIntegerField(default=1, verbose_name='eBay Store Instance Index')),
                ('ebay_category_id', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='eBay Category ID')),
                ('ebay_site_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='eBay Site ID')),
            ],
            options={
                'verbose_name': 'eBay Product',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbayStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_index', models.IntegerField(default=0)),
                ('currency_format', models.CharField(blank=True, max_length=512, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('store_hash', models.CharField(default='', editable=False, max_length=50)),
                ('auto_fulfill', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eBay Store',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbayUserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=512, verbose_name='Upload file URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebay_core.EbayProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbaySupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_guid', models.CharField(db_index=True, default=None, max_length=100, verbose_name='SureDone GUID')),
                ('product_url', models.CharField(blank=True, max_length=512, null=True)),
                ('supplier_name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('supplier_url', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=512, null=True)),
                ('variants_map', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='ebay_core.EbayStore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ebayproduct',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ebay_core.EbaySupplier'),
        ),
        migrations.AddField(
            model_name='ebayproduct',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suredone_core.SureDoneAccount'),
        ),
        migrations.AddField(
            model_name='ebayproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ebayproduct',
            name='user_supplement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplements.UserSupplement'),
        ),
        migrations.CreateModel(
            name='EbayBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('config', models.CharField(blank=True, default='', max_length=512)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('products', models.ManyToManyField(blank=True, to='ebay_core.EbayProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbayOrderTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('line_id', models.BigIntegerField()),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=512, verbose_name='Source Order ID')),
                ('source_status', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Order Status')),
                ('source_tracking', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Tracking Number')),
                ('source_status_details', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Status Details')),
                ('source_type', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Type')),
                ('hidden', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False, verbose_name='User viewed the changes')),
                ('auto_fulfilled', models.BooleanField(default=False, verbose_name='Automatically fulfilled')),
                ('check_count', models.IntegerField(default=0)),
                ('data', models.TextField(blank=True, default='')),
                ('errors', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('status_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Status Update')),
                ('product_id', models.BigIntegerField()),
                ('ebay_status', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='eBay Fulfillment Status')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebay_core.EbayStore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'index_together': {('store', 'order_id', 'line_id')},
            },
        ),
    ]
