# Generated by Django 2.2.24 on 2021-08-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0002_auto_20210828_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaystore',
            name='auth_token_exp_date',
            field=models.DateTimeField(null=True, verbose_name='Store authorization token expiration date'),
        ),
    ]
