# Generated by Django 2.2.24 on 2021-08-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0003_auto_20210828_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaystore',
            name='store_instance_id',
            field=models.IntegerField(db_index=True, editable=False, unique=True, verbose_name="Store's instance ID"),
        ),
    ]
