# Generated by Django 2.2.24 on 2021-09-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0005_auto_20210906_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebayproduct',
            old_name='ebay_product_id',
            new_name='source_id',
        ),
    ]
