# Generated by Django 2.2.24 on 2021-09-06 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0006_auto_20210906_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayproduct',
            name='sd_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Product last updated in the SureDone DB'),
            preserve_default=False,
        ),
    ]
