# Generated by Django 2.2.24 on 2021-09-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0009_ebayproduct_boards_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebaystore',
            name='auth_token_exp_date',
        ),
        migrations.AddField(
            model_name='ebaystore',
            name='legacy_auth_token_exp_date',
            field=models.DateTimeField(null=True, verbose_name='Store legacy authorization token expiration date'),
        ),
        migrations.AddField(
            model_name='ebaystore',
            name='oauth_token_exp_date',
            field=models.DateTimeField(null=True, verbose_name='Store oauth token expiration date'),
        ),
    ]
