# Generated by Django 2.2.24 on 2021-09-28 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suredone_core', '0002_auto_20210928_1213'),
        ('ebay_core', '0010_auto_20210928_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystore',
            name='sd_account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='suredone_core.SureDoneAccount', verbose_name='Parent SureDone Account'),
            preserve_default=False,
        ),
    ]
