# Generated by Django 2.2.24 on 2021-11-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0011_ebaystore_sd_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebayordertrack',
            name='product_id',
        ),
    ]
