# Generated by Django 2.2.24 on 2021-11-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0012_remove_ebayordertrack_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystore',
            name='store_username',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='eBay store username'),
        ),
    ]
