# Generated by Django 2.2.25 on 2022-01-14 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0013_ebaystore_store_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayproduct',
            name='sd_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_coreproducts', to='suredone_core.SureDoneAccount'),
        ),
        migrations.AlterField(
            model_name='ebayproduct',
            name='source_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Platform-specific Product ID'),
        ),
        migrations.AlterField(
            model_name='ebayproductvariant',
            name='source_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Platform-specific Product ID'),
        ),
        migrations.AlterField(
            model_name='ebaystore',
            name='sd_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_corestores', to='suredone_core.SureDoneAccount', verbose_name='Parent SureDone Account'),
        ),
    ]
