# Generated by Django 2.2.27 on 2022-03-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0014_auto_20220114_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayproduct',
            name='sd_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_core_products', to='suredone_core.SureDoneAccount'),
        ),
        migrations.AlterField(
            model_name='ebaystore',
            name='sd_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_core_stores', to='suredone_core.SureDoneAccount', verbose_name='Parent SureDone Account'),
        ),
    ]
