# Generated by Django 2.2.26 on 2022-02-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('last_seen', '0004_browseruseragent_useriprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='useriprecord',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
