# Generated by Django 2.2.26 on 2022-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_seen', '0005_useriprecord_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='useriprecord',
            name='city',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='useriprecord',
            name='country',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='useriprecord',
            name='org',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='browseruseragent',
            name='user_agent',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
