# Generated by Django 2.2.26 on 2022-02-14 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('last_seen', '0006_auto_20220214_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='useriprecord',
            name='extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='last_seen.ExtensionVersion'),
        ),
    ]
