# Generated by Django 3.2.13 on 2022-06-29 21:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('last_seen', '0007_auto_20220214_1641'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='lastseen',
            index_together={('user', 'module')},
        ),
    ]
