# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_subscription', '0008_auto_20181217_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStripePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Amount(in USD)')),
                ('currency', models.CharField(default='usd', max_length=15)),
                ('retail_amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('interval', models.CharField(choices=[('month', 'monthly'), ('year', 'yearly')], default='month', max_length=15)),
                ('interval_count', models.IntegerField(default=1)),
                ('trial_period_days', models.IntegerField(default=14)),
                ('statement_descriptor', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False, verbose_name='Plan is hidden')),
                ('type', models.CharField(choices=[('callflex_subscription', 'CallFlex Subscription'), ('callflex_extranumber', 'CallFlex Extra Number'), ('callflex_extraminutes', 'CallFlex Extra Minutes')], default='custom', max_length=255)),
                ('credits_data', models.TextField(blank=True, default='{}', null=True, verbose_name='Plan-specific credits set')),
                ('stripe_id', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Stripe Plan ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Plan',
                'verbose_name_plural': 'Custom Plans',
            },
        ),
        migrations.CreateModel(
            name='CustomStripeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(editable=False, max_length=255, verbose_name='Stripe Subscription ID')),
                ('subscription_item_id', models.CharField(max_length=255, null=True, verbose_name='Stripe Subscription Item ID')),
                ('status', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='Subscription Status')),
                ('data', models.TextField(blank=True, null=True)),
                ('period_start', models.DateTimeField(null=True)),
                ('period_end', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe_subscription.CustomStripePlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Subscription',
                'verbose_name_plural': 'Custom Subscriptions',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='interval',
            field=models.CharField(choices=[('month', 'monthly'), ('year', 'yearly')], default='month', max_length=15),
        ),
    ]
