# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-11 02:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bigcommerce_core', '0003_bigcommerceuserupload'),
        ('stripe_subscription', '0009_auto_20190609_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraBigCommerceStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='pending', max_length=64, null=True)),
                ('period_start', models.DateTimeField(null=True)),
                ('period_end', models.DateTimeField(null=True)),
                ('last_invoice', models.CharField(blank=True, max_length=64, null=True, verbose_name='Last Invoice Item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='bigcommerce_core.BigCommerceStore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extra BigCommerce Store',
                'verbose_name_plural': 'Extra BigCommerce Stores',
            },
        ),
    ]
