# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models


def add_fees_plan(apps, schema_editor):
    CustomStripePlan = apps.get_model('stripe_subscription', 'CustomStripePlan')
    plan = CustomStripePlan()
    plan.name = "Transaction Fee Plan"
    plan.amount = 0
    plan.currency = "usd"
    plan.retail_amount = 0
    plan.interval = "week"
    plan.interval_count = 1
    plan.trial_period_days = 0
    plan.hidden = True
    plan.type = "transactionfee_subscription"
    plan.credits_data = "{}"
    plan.stripe_id = "drop_transfee"
    plan.save()


def reverse_add_fees_plan(apps, schema_editor):
    CustomStripePlan = apps.get_model('stripe_subscription', 'CustomStripePlan')
    CustomStripePlan.objects.get(stripe_id="drop_transfee").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('stripe_subscription', '0010_extrabigcommercestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstripeplan',
            name='interval',
            field=models.CharField(choices=[('week', 'weeky'), ('month', 'monthly'), ('year', 'yearly')], default='month', max_length=15),
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='interval',
            field=models.CharField(choices=[('week', 'weeky'), ('month', 'monthly'), ('year', 'yearly')], default='month', max_length=15),
        ),
        migrations.RunPython(add_fees_plan, reverse_add_fees_plan),
    ]
