# Generated by Django 2.2.15 on 2020-08-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_subscription', '0010_extrabigcommercestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstripeplan',
            name='interval',
            field=models.CharField(choices=[('week', 'weeky'), ('month', 'monthly'), ('year', 'yearly')], default='month', max_length=15),
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='interval',
            field=models.CharField(choices=[('week', 'weeky'), ('month', 'monthly'), ('year', 'yearly')], default='month', max_length=15),
        ),
    ]
