# Generated by Django 2.2.12 on 2020-09-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_subscription', '0011_auto_20200820_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='pending', max_length=64, null=True)),
                ('period_start', models.DateTimeField(null=True)),
                ('period_end', models.DateTimeField(null=True)),
                ('last_invoice', models.CharField(blank=True, max_length=64, null=True, verbose_name='Last Invoice Item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_sub_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extra Sub User',
                'verbose_name_plural': 'Extra Sub Users',
            },
        ),
    ]
