# Generated by Django 2.2.16 on 2020-12-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_subscription', '0013_auto_20201019_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstripeplan',
            name='type',
            field=models.CharField(choices=[('callflex_subscription', 'CallFlex Subscription'), ('callflex_extranumber', 'CallFlex Extra Number'), ('callflex_extraminutes', 'CallFlex Extra Minutes'), ('addons_subscription', 'Addons Plan'), ('transactionfee_subscription', 'Transaction Fees')], default='custom', max_length=255),
        ),
    ]
