# Generated by Django 2.2.24 on 2021-08-25 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SureDoneAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_index', models.IntegerField(default=0)),
                ('currency_format', models.CharField(blank=True, max_length=512, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('api_username', models.CharField(max_length=512)),
                ('api_token', models.CharField(max_length=512)),
                ('api_version', models.CharField(default='v1', max_length=50)),
                ('api_timeout', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('store_hash', models.CharField(default='', editable=False, max_length=50)),
                ('auto_fulfill', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SureDone Account',
                'abstract': False,
            },
        ),
    ]
