# Generated by Django 2.2.24 on 2021-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suredone_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suredoneaccount',
            name='api_timeout',
        ),
        migrations.RemoveField(
            model_name='suredoneaccount',
            name='api_version',
        ),
        migrations.RemoveField(
            model_name='suredoneaccount',
            name='auto_fulfill',
        ),
        migrations.AddField(
            model_name='suredoneaccount',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='SureDone account email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suredoneaccount',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='SureDone account password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suredoneaccount',
            name='sd_id',
            field=models.CharField(default='', max_length=50, verbose_name='SureDone user ID'),
            preserve_default=False,
        ),
    ]
