# Generated by Django 2.2.24 on 2021-09-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suredone_core', '0002_auto_20210928_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='suredoneaccount',
            name='options_config_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
