# Generated by Django 2.2.24 on 2021-10-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suredone_core', '0003_suredoneaccount_options_config_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suredoneaccount',
            name='email',
            field=models.CharField(max_length=512, verbose_name='SureDone account email'),
        ),
        migrations.AlterField(
            model_name='suredoneaccount',
            name='password',
            field=models.CharField(max_length=100, verbose_name='SureDone account password'),
        ),
        migrations.AlterField(
            model_name='suredoneaccount',
            name='sd_id',
            field=models.CharField(max_length=200, verbose_name='SureDone user ID'),
        ),
    ]
