# Generated by Django 3.2.13 on 2022-06-07 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('images', models.TextField(default='[]')),
                ('product_type', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension_data', models.TextField(blank=True, default='{}', null=True)),
                ('original_url', models.TextField(blank=True, null=True)),
                ('vendor', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master Product',
                'ordering': ['-created_at'],
            },
        ),
    ]
