# Generated by Django 3.2.14 on 2022-08-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multichannel_products_core', '0002_masterproduct_variants_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProductSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(blank=True, max_length=512, null=True)),
                ('supplier_name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('supplier_url', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=512, null=True)),
                ('variants_map', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multichannel_products_core.masterproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multichannel_products_core.masterproductsupplier'),
        ),
    ]
