# Generated by Django 3.2.14 on 2022-08-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('multichannel_products_core', '0003_auto_20220819_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('title_and_description', 'Title & Description'), ('pricing', 'Pricing')], default='title_and_description', max_length=32)),
                ('name', models.CharField(default='Template Name', max_length=255)),
                ('title', models.TextField(blank=True, default='{{ title }}', null=True)),
                ('description', models.TextField(blank=True, default='{{ description }}', null=True)),
                ('price_override_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('price_modifier', models.CharField(choices=[('$', '$'), ('%', '%')], default='$', max_length=1)),
                ('price_direction', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('price_status', models.CharField(choices=[('inactive', 'Inactive'), ('active_override', 'Active Override'), ('active_calculated', 'Active Calculated')], default='inactive', max_length=32)),
                ('compare_price_override_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('compare_price_modifier', models.CharField(choices=[('$', '$'), ('%', '%')], default='$', max_length=1)),
                ('compare_price_direction', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1)),
                ('compare_price_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('compare_price_status', models.CharField(choices=[('inactive', 'Inactive'), ('active_override', 'Active Override'), ('active_calculated', 'Active Calculated')], default='inactive', max_length=32)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
