# Generated by Django 3.2.14 on 2022-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichannel_products_core', '0004_producttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
