# Generated by Django 2.2.25 on 2022-01-14 02:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplements', '0089_merge_20211013_1610'),
        ('suredone_core', '0004_auto_20211013_2123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FBProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('product_type', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('boards_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('data', models.TextField(blank=True, default='{}', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('config', models.TextField(blank=True, null=True)),
                ('variants_map', models.TextField(blank=True, default='')),
                ('supplier_map', models.TextField(blank=True, default='', null=True)),
                ('shipping_map', models.TextField(blank=True, default='', null=True)),
                ('bundle_map', models.TextField(blank=True, null=True)),
                ('mapping_config', models.TextField(blank=True, null=True)),
                ('monitor_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SureDone GUID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SureDone SKU')),
                ('source_id', models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Platform-specific Product ID')),
                ('product_description', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, default='New', max_length=255)),
                ('thumbnail_image', models.TextField(blank=True, null=True, verbose_name="Product's main thumbnail image")),
                ('media_links_data', models.TextField(blank=True, null=True, verbose_name="Product's media links in a JSON string")),
                ('variants_config', models.TextField(null=True)),
                ('sd_updated_at', models.DateTimeField(null=True, verbose_name='Product last updated in the SureDone DB')),
                ('fb_store_index', models.BigIntegerField(default=1, verbose_name='Facebook Store Instance Index')),
                ('fb_category_id', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Facebook Category ID')),
            ],
            options={
                'verbose_name': 'Facebook Product',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FBStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_index', models.IntegerField(default=0)),
                ('currency_format', models.CharField(blank=True, max_length=512, null=True)),
                ('store_instance_id', models.IntegerField(db_index=True, editable=False, verbose_name="Store's instance ID")),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('store_hash', models.CharField(default='', editable=False, max_length=50)),
                ('auto_fulfill', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Facebook store name')),
                ('sd_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_corestores', to='suredone_core.SureDoneAccount', verbose_name='Parent SureDone Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Store',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FBUserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=512, verbose_name='Upload file URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_core.FBProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FBSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_guid', models.CharField(db_index=True, default=None, max_length=100, verbose_name='SureDone GUID')),
                ('product_url', models.CharField(blank=True, max_length=512, null=True)),
                ('supplier_name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('supplier_url', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=512, null=True)),
                ('variants_map', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_core.FBProduct', to_field='guid')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='facebook_core.FBStore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fbproduct',
            name='default_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facebook_core.FBSupplier'),
        ),
        migrations.AddField(
            model_name='fbproduct',
            name='sd_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_coreproducts', to='suredone_core.SureDoneAccount'),
        ),
        migrations.AddField(
            model_name='fbproduct',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='facebook_core.FBStore'),
        ),
        migrations.AddField(
            model_name='fbproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbproduct',
            name='user_supplement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplements.UserSupplement'),
        ),
        migrations.CreateModel(
            name='FBBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('config', models.CharField(blank=True, default='', max_length=512)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('products', models.ManyToManyField(blank=True, to='facebook_core.FBProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FBOrderTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=512, verbose_name='Source Order ID')),
                ('source_status', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Order Status')),
                ('source_tracking', models.CharField(blank=True, default='', max_length=128, verbose_name='Source Tracking Number')),
                ('source_status_details', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Status Details')),
                ('source_type', models.CharField(blank=True, max_length=512, null=True, verbose_name='Source Type')),
                ('hidden', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False, verbose_name='User viewed the changes')),
                ('auto_fulfilled', models.BooleanField(default=False, verbose_name='Automatically fulfilled')),
                ('check_count', models.IntegerField(default=0)),
                ('data', models.TextField(blank=True, default='')),
                ('errors', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('status_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Status Update')),
                ('line_id', models.CharField(blank=True, db_index=True, default='', max_length=512, verbose_name='Variant-specific GUID')),
                ('fb_status', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Facebook Fulfillment Status')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_core.FBStore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'index_together': {('store', 'order_id', 'line_id')},
            },
        ),
        migrations.AddField(
            model_name='fbproduct',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook product brand'),
        ),
        migrations.AddField(
            model_name='fbproduct',
            name='page_link',
            field=models.CharField(blank=True, default='', max_length=510, verbose_name='Product page link'),
        ),
        migrations.AddField(
            model_name='fbproduct',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Product publication status on Facebook'),
        ),
        migrations.CreateModel(
            name='FBProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SureDone GUID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SureDone SKU')),
                ('variant_title', models.CharField(blank=True, max_length=512, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.TextField(blank=True, null=True)),
                ('supplier_sku', models.CharField(blank=True, max_length=512, null=True)),
                ('source_id', models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Platform-specific Product ID')),
                ('variant_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facebook_core.FBSupplier', verbose_name='Variant-specific Supplier')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='facebook_core.FBProduct', to_field='guid', verbose_name='Parent Product')),
                ('status', models.CharField(blank=True, default='', max_length=50, verbose_name='Product publication status on Facebook')),
            ],
            options={
                'verbose_name': 'Facebook Product Variant',
                'ordering': ['created_at'],
            },
        ),
    ]
