# Generated by Django 2.2.27 on 2022-02-28 02:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_core', '0002_fbstore_commerce_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbstore',
            name='creds',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Facebook creds'),
        ),
    ]
