# Generated by Django 2.2.27 on 2022-03-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_core', '0004_fbproduct_last_export_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbproduct',
            name='sd_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_core_products', to='suredone_core.SureDoneAccount'),
        ),
        migrations.AlterField(
            model_name='fbstore',
            name='sd_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_core_stores', to='suredone_core.SureDoneAccount', verbose_name='Parent SureDone Account'),
        ),
    ]
