# Generated by Django 2.2.27 on 2022-03-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_core', '0005_auto_20220317_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbstore',
            name='business_manager_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Facebook Business Manager ID'),
        ),
        migrations.AddField(
            model_name='fbstore',
            name='catalog_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Facebook Catalog ID'),
        ),
    ]
