# Generated by Django 3.2.13 on 2022-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_core', '0006_auto_20220323_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbstore',
            name='creds',
            field=models.JSONField(default=dict, verbose_name='Facebook creds'),
        ),
    ]
