# Generated by Django 3.2.13 on 2022-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_core', '0007_alter_fbstore_creds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbproduct',
            name='fb_category_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook category name'),
        ),
    ]
