# Generated by Django 3.2.13 on 2022-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_core', '0008_fbproduct_fb_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbproduct',
            name='fb_category_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Facebook category name'),
        ),
    ]
