# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysubscription',
            name='charge_type',
            field=models.CharField(choices=[(b'recurring', b'Recurring'), (b'single', b'Single Charge')], default=b'recurring', max_length=25),
        ),
    ]
