# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0186_groupplanchangelog'),
        ('shopify_subscription', '0002_shopifysubscription_charge_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremetricsCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_oid', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baremetrics_customer', to='leadgalaxy.ShopifyStore')),
            ],
        ),
        migrations.CreateModel(
            name='BaremetricsSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_oid', models.CharField(max_length=50)),
                ('canceled_at', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='shopify_subscription.BaremetricsCustomer')),
                ('shopify_subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baremetrics_subscription', to='shopify_subscription.ShopifySubscription')),
            ],
        ),
    ]
