# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_subscription', '0003_baremetricscustomer_baremetricssubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremetricsCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_oid', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='shopify_subscription.BaremetricsCustomer')),
            ],
        ),
    ]
