# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_subscription', '0004_baremetricscharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='baremetricssubscription',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Shopify Charge Status'),
        ),
    ]
