# Generated by Django 2.2.16 on 2021-01-27 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopify_subscription', '0005_baremetricssubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysubscription',
            name='update_capped_amount_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShopifySubscriptionWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=255, unique=True, verbose_name='Charge ID for re-activation')),
                ('confirmation_url', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('next_warning', models.DateField(blank=True, null=True)),
                ('shopify_subscription', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='warning',
                    to='shopify_subscription.ShopifySubscription'
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='shopify_subscription_warning',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
