# Generated by Django 3.2.13 on 2022-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleproduct',
            name='google_category_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Google category name'),
        ),
    ]
