# Generated by Django 3.2.13 on 2022-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_core', '0002_googleproduct_google_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlestore',
            name='creds',
            field=models.JSONField(default=dict, verbose_name='Google creds'),
        ),
    ]
