# Generated by Django 3.2.13 on 2022-07-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multichannel_products_core', '0002_masterproduct_variants_config'),
        ('google_core', '0003_alter_googlestore_creds'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleproduct',
            name='master_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='multichannel_products_core.masterproduct'),
        ),
    ]
