# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadgalaxy', '0129_shopifyproduct_original_data_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClippingMagic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(default=b'', max_length=100, verbose_name=b'ClippingMagic API ID')),
                ('api_secret', models.CharField(default=b'', max_length=255, verbose_name=b'ClippingMagic API Secret')),
                ('allowed_images', models.IntegerField(default=-1)),
                ('downloaded_images', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'Last update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clippingmagic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
