# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0176_auto_20180220_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='delete_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
