# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0177_shopifystore_delete_request_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='payment_interval',
            field=models.CharField(choices=[(b'monthly', b'Monthly'), (b'yearly', b'Yearly'), (b'lifetime', b'Lifetime')], default=b'', max_length=25),
        ),
    ]
