# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0178_groupplan_payment_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='plan_description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name=b'Plan description in in Plans Page'),
        ),
        migrations.AddField(
            model_name='groupplan',
            name='price_info',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name=b'Price info in Plans Page'),
        ),
        migrations.AddField(
            model_name='groupplan',
            name='retail_price_info',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name=b'Retail Price info in Plans Page'),
        ),
    ]
