# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 17:16
from __future__ import unicode_literals

from django.db import migrations


def add_new_permission(apps, schema_editor):
    AppPermission = apps.get_model("leadgalaxy", "AppPermission")
    FeatureBundle = apps.get_model("leadgalaxy", "FeatureBundle")

    permission = AppPermission.objects.create(
        name='ebay_auto_fulfill.use',
        description='eBay Auto Fulfill')

    bundle = FeatureBundle.objects.create(
        title='eBay Auto Fulfill Tester',
        slug='ebay-auto-fulfill-tester',
        hidden_from_user=True)

    bundle.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0179_auto_20181121_1601'),
    ]

    operations = [
        migrations.RunPython(add_new_permission),
    ]
