# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0180_auto_20181210_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name=b'User Tags'),
        ),
    ]
