# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0181_userprofile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyordertrack',
            name='source_status_details',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name=b'Source Status Details'),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='product_type',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='tag',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
