# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-28 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0182_auto_20190123_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifyproductexport',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopifyproductexport',
            name='store',
        ),
        migrations.RemoveField(
            model_name='shopifyproduct',
            name='shopify_export',
        ),
        migrations.DeleteModel(
            name='ShopifyProductExport',
        ),
    ]
