# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-30 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0183_auto_20190128_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyboard',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
