# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0184_shopifyboard_favorite'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='aliexpressproductchange',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='aliexpressproductchange',
            name='product',
        ),
        migrations.RemoveField(
            model_name='aliexpressproductchange',
            name='user',
        ),
        migrations.DeleteModel(
            name='AliexpressProductChange',
        ),
    ]
