# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-19 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadgalaxy', '0185_remove_aliexpressproductchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPlanChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(blank=True, null=True, verbose_name=b'When Plan Changed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leadgalaxy.GroupPlan')),
                ('previous_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_plan', to='leadgalaxy.GroupPlan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
