# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groovekart_core', '0001_initial'),
        ('leadgalaxy', '0186_groupplanchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubuserGKartPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subuser_gkart_permissions', to='groovekart_core.GrooveKartStore')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subuser_gkart_stores',
            field=models.ManyToManyField(blank=True, related_name='subuser_gkart_stores', to='groovekart_core.GrooveKartStore'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subuser_gkart_permissions',
            field=models.ManyToManyField(blank=True, to='leadgalaxy.SubuserGKartPermission'),
        ),
        migrations.AlterUniqueTogether(
            name='subusergkartpermission',
            unique_together=set([('codename', 'store')]),
        ),
    ]
