# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0189_auto_20190325_2116'),
        ('leadgalaxy', '0187_auto_20190423_0113'),
    ]

    operations = [
    ]
