# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0190_merge_20190502_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='uninstall_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
