# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-25 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0192_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='free_plan',
            field=models.BooleanField(default=True),
        ),
    ]
