# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-19 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0194_auto_20191219_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
