# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-21 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0197_auto_20191220_1454'),
        ('leadgalaxy', '0194_auto_20190912_0200'),
    ]

    operations = [
    ]
