# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-31 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0199_userblacksampletracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblacksampletracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL),
        ),
    ]
