# Generated by Django 2.2.12 on 2020-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0203_accountregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountregistration',
            name='register_hash',
            field=models.TextField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accountregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
