# Generated by Django 2.2.12 on 2020-06-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0204_auto_20200518_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemarkuprule',
            name='markup_compare_value',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='pricemarkuprule',
            name='markup_value',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
