# Generated by Django 2.2.12 on 2020-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0205_auto_20200610_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='extra_store_cost',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=9, null=True, verbose_name='Extra store cost per store(in USD)'),
        ),
    ]
