# Generated by Django 2.2.12 on 2020-07-28 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadgalaxy', '0205_auto_20200610_1513'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='groupplan',
            name='sales_fee_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    to='fulfilment_fee.SalesFeeConfig',
                                    verbose_name='Sales fee config (requires `sales_fee.use` permission)'),
        ),
       
    ]