# Generated by Django 2.2.13 on 2020-08-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0208_groupplan_support_addons'),
        ('leadgalaxy', '0206_auto_20200803_0858'),
    ]

    operations = [
    ]
