# Generated by Django 2.2.15 on 2020-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0208_groupplan_support_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='unique_supplements',
            field=models.IntegerField(default=0, verbose_name='Unique Supplements Limit'),
        ),
        migrations.AddField(
            model_name='groupplan',
            name='user_supplements',
            field=models.IntegerField(default=0, verbose_name='User Supplements Limit'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unique_supplements',
            field=models.IntegerField(default=-2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_supplements',
            field=models.IntegerField(default=-2),
        ),
    ]
