# Generated by Django 2.2.15 on 2020-08-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment_fee', '0001_initial'),
        ('leadgalaxy', '0209_auto_20200812_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='sales_fee_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfilment_fee.SalesFeeConfig'),
        ),
    ]
