# Generated by Django 2.2.16 on 2020-10-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0211_auto_20200826_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='extra_subuser_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Extra sub user cost per user(in USD)'),
        ),
        migrations.AddField(
            model_name='groupplan',
            name='extra_subusers',
            field=models.BooleanField(default=True, verbose_name='Support adding extra sub users'),
        ),
        migrations.AddField(
            model_name='groupplan',
            name='sub_users_limit',
            field=models.IntegerField(default=-1, verbose_name='Sub Users Limit'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_users_limit',
            field=models.IntegerField(default=-2),
        ),
    ]
