# Generated by Django 2.2.16 on 2020-11-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0212_auto_20201009_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='private_label',
            field=models.NullBooleanField(default=False, verbose_name='Using Private Label App'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private_label',
            field=models.NullBooleanField(default=False, verbose_name='Using Private Label App'),
        ),
    ]
