# Generated by Django 2.2.16 on 2020-11-05 02:20
from django.db import migrations, models


def attach_current_goals_to_plans(apps, schema_editor):
    GroupPlan = apps.get_model('leadgalaxy', 'GroupPlan')
    Goal = apps.get_model('goals', 'Goal')
    for plan in GroupPlan.objects.all():
        for goal in Goal.objects.all():
            plan.goals.add(goal)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_add_viewed_to_goals'),
        ('leadgalaxy', '0212_auto_20201009_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='plans', to='goals.Goal'),
        ),
        migrations.RunPython(attach_current_goals_to_plans)
    ]
