# Generated by Django 2.2.16 on 2020-12-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        GroupPlan = apps.get_model('leadgalaxy', 'GroupPlan')
        plans = list(GroupPlan.objects.all())
        DashboardVideo = apps.get_model('leadgalaxy', 'DashboardVideo')
        for video in DashboardVideo.objects.all():
            video.plans.add(*plans)

    def reverse_func(apps, schema_editor):
        GroupPlan = apps.get_model('leadgalaxy', 'GroupPlan')
        plans = list(GroupPlan.objects.all())
        DashboardVideo = apps.get_model('leadgalaxy', 'DashboardVideo')
        for video in DashboardVideo.objects.all():
            video.plans.remove(*plans)

    dependencies = [
        ('leadgalaxy', '0214_auto_20201127_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardvideo',
            name='plans',
            field=models.ManyToManyField(blank=True, to='leadgalaxy.GroupPlan'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
