# Generated by Django 2.2.16 on 2021-01-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0215_dashboardvideo_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='show_in_plod_app',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Show in PLoD App Listing'),
        ),
    ]
