# Generated by Django 2.2.18 on 2021-04-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0217_userprofile_has_churnzero_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='revision',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
