# Generated by Django 2.2.18 on 2021-05-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0218_groupplan_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dropified_private_label',
            field=models.NullBooleanField(default=False, verbose_name='PLOD user on Dropified App'),
        ),
    ]
