# Generated by Django 2.2.18 on 2021-05-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0219_userprofile_dropified_private_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='private_label',
            field=models.BooleanField(default=False, verbose_name='Private Label Plan'),
        ),
    ]
