# Generated by Django 2.2.18 on 2021-05-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0220_groupplan_private_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='single_charge',
            field=models.BooleanField(default=False),
        ),
    ]
