# Generated by Django 2.2.24 on 2021-06-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0222_auto_20210615_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='data',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='title',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
