# Generated by Django 2.2.24 on 2021-06-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0224_auto_20210627_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
