# Generated by Django 2.2.24 on 2021-07-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0226_groupplan_parent_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='index_products',
            field=models.BooleanField(default=False, verbose_name='Index user products'),
        ),
    ]
