# Generated by Django 2.2.24 on 2021-08-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0002_auto_20210828_2040'),
        ('leadgalaxy', '0227_userprofile_subuser_suredone_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subuser_suredone_accounts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subuser_ebay_stores',
            field=models.ManyToManyField(blank=True, related_name='subuser_ebay_stores', to='ebay_core.EbayStore'),
        ),
    ]
