# Generated by Django 2.2.24 on 2021-08-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0228_shopifyproduct_boards_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='index_products',
            field=models.BooleanField(default=False, null=True, verbose_name='Index user products'),
        ),
    ]
