# Generated by Django 2.2.24 on 2021-09-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0228_auto_20210828_2040'),
        ('leadgalaxy', '0229_auto_20210818_1355'),
    ]

    operations = [
    ]
