# Generated by Django 2.2.24 on 2021-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0232_shopifystore_hubspot_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifystore',
            name='hubspot_title',
        ),
        migrations.AddField(
            model_name='groupplan',
            name='hubspot_title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
