# Generated by Django 2.2.25 on 2022-01-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_core', '__first__'),
        ('leadgalaxy', '0233_auto_20211203_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subuser_fb_stores',
            field=models.ManyToManyField(blank=True, related_name='subuser_fb_stores', to='facebook_core.FBStore'),
        ),
    ]
