# Generated by Django 2.2.24 on 2022-01-24 12:28

from django.db import migrations


def forwards_func(apps, schema_editor):
    AppPermission = apps.get_model('leadgalaxy', 'AppPermission')
    AppPermission.objects.create(name='dashboard.view')


def reverse_func(apps, schema_editor):
    AppPermission = apps.get_model('leadgalaxy', 'AppPermission')
    AppPermission.objects.filter(name='dashboard.view').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0233_auto_20211203_1823'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
