# Generated by Django 2.2.25 on 2022-02-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0234_auto_20220124_1228'),
        ('leadgalaxy', '0234_userprofile_subuser_fb_stores'),
    ]

    operations = [
    ]
