# Generated by Django 2.2.26 on 2022-02-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0235_merge_20220211_0000'),
        ('leadgalaxy', '0234_auto_20220223_0118'),
    ]

    operations = [
    ]
