# Generated by Django 3.2.13 on 2022-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0236_merge_20220223_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproduct',
            name='is_excluded',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='shopifystore',
            name='private_label',
            field=models.BooleanField(default=False, null=True, verbose_name='Using Private Label App'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dropified_private_label',
            field=models.BooleanField(default=False, null=True, verbose_name='PLOD user on Dropified App'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='private_label',
            field=models.BooleanField(default=False, null=True, verbose_name='Using Private Label App'),
        ),
    ]
