# Generated by Django 3.2.13 on 2022-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0237_auto_20220421_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupplan',
            name='show_in_plod_app',
            field=models.IntegerField(choices=[(0, "Don't show for PLOD"), (1, 'Show for PLOD only'), (3, 'Show For All Users')], default=0, verbose_name='Show in PLoD App Listing'),  # noqa
        ),
    ]
