# Generated by Django 3.2.13 on 2022-05-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0238_alter_groupplan_show_in_plod_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupplan',
            options={'ordering': ['title']},
        ),
    ]
