# Generated by Django 3.2.13 on 2022-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_marketplace_core', '0001_initial'),
        ('leadgalaxy', '0239_alter_groupplan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subuser_fb_marketplace_stores',
            field=models.ManyToManyField(blank=True, related_name='subuser_fb_marketplace_stores', to='fb_marketplace_core.FBMarketplaceStore'),
        ),
    ]
