# Generated by Django 3.2.13 on 2022-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0240_userprofile_subuser_fb_marketplace_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='show_fulfillment_fee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupplan',
            name='show_stores_count',
            field=models.BooleanField(default=True),
        ),
    ]
