# Generated by Django 2.2.27 on 2022-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_core', '0001_initial'),
        ('leadgalaxy', '0241_auto_20220613_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subuser_google_stores',
            field=models.ManyToManyField(blank=True, related_name='subuser_google_stores', to='google_core.GoogleStore'),
        ),
    ]
