# Generated by Django 3.2.13 on 2022-06-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_common', '0016_auto_20220331_1659'),
        ('leadgalaxy', '0242_userprofile_subuser_google_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supplier',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='linked_supplier',
                                    to='product_common.productsupplier',
                                    verbose_name='Linked Supplier'),
        ),
    ]
