# Generated by Django 3.2.13 on 2022-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0242_userprofile_subuser_google_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupplan',
            name='slug',
            field=models.SlugField(max_length=512, unique=True, verbose_name='Plan Slug'),
        ),
    ]
