# Generated by Django 3.2.13 on 2022-07-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        AppPermission = apps.get_model("leadgalaxy", "AppPermission")
        db_alias = schema_editor.connection.alias
        AppPermission.objects.using(db_alias).create(name='pls_supplier.use', description='PLS Supplier')

    dependencies = [
        ('leadgalaxy', '0243_userprofile_supplier'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
