# Generated by Django 3.2.13 on 2022-07-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0243_alter_groupplan_slug'),
        ('leadgalaxy', '0244_auto_20220705_1743'),
    ]

    operations = [
    ]
