# Generated by Django 3.2.13 on 2022-07-19 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_core', '0009_alter_fbproduct_fb_category_name'),
        ('leadgalaxy', '0245_merge_20220713_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubuserFBPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='subuser_fb_permissions', to='facebook_core.fbstore')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('codename', 'store')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subuser_fb_permissions',
            field=models.ManyToManyField(blank=True, to='leadgalaxy.SubuserFBPermission'),
        ),
    ]
