# Generated by Django 3.2.13 on 2022-07-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_core', '0015_auto_20220317_0236'),
        ('leadgalaxy', '0245_merge_20220713_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubuserEbayPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subuser_ebay_permissions', to='ebay_core.ebaystore')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('codename', 'store')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subuser_ebay_permissions',
            field=models.ManyToManyField(blank=True, to='leadgalaxy.SubuserEbayPermission'),
        ),
    ]
