# Generated by Django 3.2.13 on 2022-07-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0096_auto_20220704_1018'),
        ('leadgalaxy', '0245_merge_20220713_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='warehouse_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_warehouse', to='supplements.shipstationaccount', verbose_name='Linked Warehouse'),
        ),
    ]
