# Generated by Django 3.2.13 on 2022-07-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0246_auto_20220719_0054'),
        ('leadgalaxy', '0246_auto_20220721_1052'),
    ]

    operations = [
    ]
