# Generated by Django 3.2.13 on 2022-07-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0246_userprofile_warehouse_account'),
        ('leadgalaxy', '0247_merge_0246_auto_20220719_0054_0246_auto_20220721_1052'),
    ]

    operations = [
    ]
