# Generated by Django 3.2.13 on 2022-07-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0246_auto_20220718_1947'),
        ('leadgalaxy', '0247_merge_0246_auto_20220719_0054_0246_auto_20220721_1052'),
    ]

    operations = [
    ]
