# Generated by Django 3.2.13 on 2022-07-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0248_merge_20220725_2337'),
        ('leadgalaxy', '0248_merge_20220726_0659'),
    ]

    operations = [
    ]
