# Generated by Django 3.2.14 on 2022-08-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0249_merge_20220726_1832'),
        ('leadgalaxy', '0249_merge_20220727_2048'),
    ]

    operations = [
    ]
