# Generated by Django 3.2.13 on 2022-08-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0249_merge_20220726_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='suredone_orders_limit',
            field=models.IntegerField(default=-1, verbose_name='Suredone Orders Limit'),
        ),
    ]
