# Generated by Django 3.2.14 on 2022-08-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0250_groupplan_suredone_orders_limit'),
        ('leadgalaxy', '0250_merge_20220812_1840'),
    ]

    operations = [
    ]
