# Generated by Django 3.2.14 on 2022-08-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multichannel_products_core', '0003_auto_20220819_1333'),
        ('leadgalaxy', '0250_merge_20220812_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyproduct',
            name='master_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multichannel_products_core.masterproduct'),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='master_variants_map',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
