# Generated by Django 3.2.14 on 2022-08-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0251_auto_20220820_1209'),
        ('leadgalaxy', '0251_merge_20220815_0217'),
    ]

    operations = [
    ]
