# Generated by Django 3.2.14 on 2022-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0252_merge_20220830_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='product_update_limit',
            field=models.IntegerField(default=10000, verbose_name='Product Update Limit'),
        ),
    ]
