# Generated by Django 3.2.14 on 2022-09-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0253_groupplan_product_update_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupplan',
            name='product_create_limit',
            field=models.IntegerField(default=10000, verbose_name='Products Create Limit'),
        ),
    ]
