# Generated by Django 3.2.14 on 2022-09-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0255_auto_20220912_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_level',
            field=models.IntegerField(default=1, null=True, verbose_name='Onboarding Level'),
        ),
    ]
