# Generated by Django 3.2.14 on 2022-10-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0256_userprofile_onboarding_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppermission',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
