# Generated by Django 3.2.16 on 2022-10-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0259_auto_20221026_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_new_layout',
            field=models.BooleanField(default=True),
        ),
    ]
