# Generated by Django 3.2.15 on 2022-10-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0259_auto_20221026_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupplan',
            name='product_create_limit',
            field=models.IntegerField(default=10000, verbose_name='Suredone Products Create Limit'),
        ),
        migrations.AlterField(
            model_name='groupplan',
            name='product_update_limit',
            field=models.IntegerField(default=10000, verbose_name='Suredone Product Update Limit'),
        ),
    ]
