# Generated by Django 3.2.16 on 2022-10-27 09:59
import json

from django.db import migrations


def update_user_config(apps, schema_editor):
    UserProfile = apps.get_model('leadgalaxy', 'UserProfile')
    for profile in UserProfile.objects.all():
        try:
            config = json.loads(profile.config)
        except:
            config = {}
        config['revert_to_v2210311'] = True
        profile.config = json.dumps(config)
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0260_userprofile_show_new_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='show_new_layout',
        ),
        migrations.RunPython(update_user_config),
    ]
