# Generated by Django 3.2.14 on 2022-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0261_remove_userprofile_show_new_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupplan',
            name='product_create_limit',
            field=models.IntegerField(default=10000, verbose_name='Suredone Products Create Limit'),
        ),
        migrations.AlterField(
            model_name='groupplan',
            name='product_update_limit',
            field=models.IntegerField(default=10000, verbose_name='Suredone Product Update Limit'),
        ),
    ]
