# Generated by Django 3.2.14 on 2022-11-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgalaxy', '0262_auto_20221111_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='dropified_fulfillment_service',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='dropified_location',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
